package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.Alarm;
import net.muratec.mcs.model.AlarmExample;
import org.apache.ibatis.annotations.Param;

public interface AlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    long countByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    int deleteByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    int insert(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    int insertSelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    List<Alarm> selectByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALARM
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Alarm record, @Param("example") AlarmExample example);
}