package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.maint.ReqAmhsConfigurationEntity;
import net.muratec.mcs.entity.maint.ReqGetAmhsConfigEntity;
import net.muratec.mcs.model.Amhs;
import net.muratec.mcs.model.AmhsExample;
import net.muratec.mcs.model.AmhsModel;

public interface AmhsMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    long countByExample(AmhsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int deleteByExample(AmhsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int deleteByPrimaryKey(String amhsId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int insert(Amhs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int insertSelective(Amhs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    List<Amhs> selectByExample(AmhsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    Amhs selectByPrimaryKey(String amhsId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Amhs record, @Param("example") AmhsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int updateByExample(@Param("record") Amhs record, @Param("example") AmhsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Amhs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AMHS
     * @mbg.generated
     */
    int updateByPrimaryKey(Amhs record);

    // =============================
    // MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Amsh List by AmhsType
     * @param       cond   (search criteria)
     * @return      Amhs List
     * @retval      List of AmhsModel Style
     * @attention
     * @note        Select Amsh List by AmhsType.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<AmhsModel> selectByAmhsType(ReqGetAmhsConfigEntity cond);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Check 'ConnectPort' Uniquery
     * @param       reqEntity   (search criteria)
     * @return      the number of Amhs List that matches ConnectPort
     * @retval      long Style
     * @attention
     * @note
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    long checkUniqueConnectPort(ReqAmhsConfigurationEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get AMHS List by AMHS_TYPE
     * @param       amhsType   (search criterion)
     * @return      AMHS List
     * @retval      List of AmhsModel Style
     * @attention
     * @note        Get AMHS List by AMHS_TYPE.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<AmhsModel> getAmhsByType(@Param("amhsType") Short amhsType);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Stocker Controller
     * @param
     * @return      AMHS List
     * @retval      List of AmhsModel Style
     * @attention
     * @note        Get Stocker Controller
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<Amhs> selectSTKControllerList();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Floor Transfer Controller
     * @param
     * @return      String List
     * @retval      List of String
     * @attention
     * @note        Get Floor Transfer Controller
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectFloorTransferControllerList();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Floor Transfer Controller
     * @param
     * @return      String List
     * @retval      List of String
     * @attention
     * @note        Get Floor Transfer Controller
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectEQPControllerListByFloor(@Param("floor") Short floor);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Get Floor Transfer Controller
     * @param
     * @return      String List
     * @retval      List of String
     * @attention
     * @note        Get Floor Transfer Controller
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<String> selectOPCControllerListByFloor(@Param("floor") Short floor);
}
