package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.hist.ReqGetAtomicActivityHistEntity;
import net.muratec.mcs.entity.hist.ReqGetMacroDataEntity;
import net.muratec.mcs.entity.info.ReqGetHostCommInfoEntity;
import net.muratec.mcs.model.AtomicTransferLog;
import net.muratec.mcs.model.AtomicTransferLogExample;
import net.muratec.mcs.model.AtomicTransferLogKey;
import net.muratec.mcs.model.Host;
import net.muratec.mcs.model.MacroTransferLog;
import net.muratec.mcs.model.Ohb;
import net.muratec.mcs.model.Port;
import net.muratec.mcs.model.Tsc;

import org.apache.commons.httpclient.methods.multipart.Part;
import org.apache.ibatis.annotations.Param;

public interface AtomicTransferLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int countByExample(AtomicTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int deleteByExample(AtomicTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int deleteByPrimaryKey(AtomicTransferLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int insert(AtomicTransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int insertSelective(AtomicTransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    List<AtomicTransferLog> selectByExample(AtomicTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    AtomicTransferLog selectByPrimaryKey(AtomicTransferLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") AtomicTransferLog record, @Param("example") AtomicTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int updateByExample(@Param("record") AtomicTransferLog record, @Param("example") AtomicTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int updateByPrimaryKeySelective(AtomicTransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATOMIC_TRANSFER_LOG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    int updateByPrimaryKey(AtomicTransferLog record);
    // STD 2020.03.26 董 天津村研  MCSV4　GUI開発  Ver2.0 Rev.000 
    List<AtomicTransferLog> selectAtomicActivityHistList(ReqGetAtomicActivityHistEntity reqEntity);
    List<AtomicTransferLog> selectAtomicActivityHistList();
    List<Tsc> selectTscNameList();
    List<Tsc> selectStkData();
    List<Ohb> selectOhbData();
    List<Port> selectPortData();
    int getCount(ReqGetAtomicActivityHistEntity record);
//    List<MacroTransferLog> selectMacroDataList(ReqGetMacroDataEntity reqEntity);
    // END 2020.03.26 董 天津村研  MCSV4　GUI開発  Ver2.0 Rev.000 

}