package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.info.GroupPortListEntity;
import net.muratec.mcs.entity.info.ReqGetCarrierListEntity;
import net.muratec.mcs.model.Carrier;
import net.muratec.mcs.model.CarrierExample;
import net.muratec.mcs.model.CarrierModel;

public interface CarrierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    long countByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int deleteByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carrierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int insert(Carrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int insertSelective(Carrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    List<Carrier> selectByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    Carrier selectByPrimaryKey(String carrierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Carrier record, @Param("example") CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Carrier record, @Param("example") CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Carrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARRIER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Carrier record);
    
    List<CarrierModel> selectList(ReqGetCarrierListEntity reqEntity);
    int getCount(ReqGetCarrierListEntity reqEntity);
    List<GroupPortListEntity> selectgetGroupIdList(@Param("portId") String portId);
}