package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.define.ReqGetDefineLLCComEntity;
import net.muratec.mcs.model.ComConf;
import net.muratec.mcs.model.ComConfExample;

import org.apache.ibatis.annotations.Param;

public interface ComConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int countByExample(ComConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int deleteByExample(ComConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int deleteByPrimaryKey(Integer llcSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int insert(ComConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int insertSelective(ComConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    List<ComConf> selectByExample(ComConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    ComConf selectByPrimaryKey(Integer llcSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") ComConf record, @Param("example") ComConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int updateByExample(@Param("record") ComConf record, @Param("example") ComConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int updateByPrimaryKeySelective(ComConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_CONF
     *
     * @mbggenerated Fri May 08 15:28:42 CST 2020
     */
    int updateByPrimaryKey(ComConf record);
    List<ComConf> selectDefineLLCCom(ReqGetDefineLLCComEntity reqEntity);
    int getCount(ReqGetDefineLLCComEntity record);
}