package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.common.AjaxDataTablesReqBaseEntity;
import net.muratec.mcs.model.JobPriority;
import net.muratec.mcs.model.JobPriorityExample;
import net.muratec.mcs.model.JobPriorityModel;

public interface JobPriorityMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    long countByExample(JobPriorityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int deleteByExample(JobPriorityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short thresholdPriority);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int insert(JobPriority record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int insertSelective(JobPriority record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    List<JobPriority> selectByExample(JobPriorityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    JobPriority selectByPrimaryKey(Short thresholdPriority);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JobPriority record, @Param("example") JobPriorityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int updateByExample(@Param("record") JobPriority record, @Param("example") JobPriorityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JobPriority record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table JOB_PRIORITY
     * @mbg.generated
     */
    int updateByPrimaryKey(JobPriority record);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectMinPriority (Get the minimum value of THRESHOLD_PRIORITY for each HOTLOT_CATEGORY)function
     * @param
     * @return    The minimum value of THRESHOLD_PRIORITY of each HOTLOT_CATEGORY
     * @retval    Return the minimum value of THRESHOLD_PRIORITY for each HOTLOT_CATEGORY
     * @attention
     * @note      Use model of automatically generated JOB_PRIORITY table as return value
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<JobPriority> selectMinPriority();

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectJobPriorityList
     * @param     reqEntiry  Request from client
     * @return    jobPriorityList
     * @retval    List
     * @attention
     * @note      Get JobPriority List
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<JobPriorityModel> selectJobPriorityList(AjaxDataTablesReqBaseEntity reqEntity);
}
