package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.info.ReqGetOhbInfoListEntity;
import net.muratec.mcs.model.Ohb;
import net.muratec.mcs.model.OhbExample;
import net.muratec.mcs.model.OhbModel;

import org.apache.ibatis.annotations.Param;

public interface OhbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    long countByExample(OhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int deleteByExample(OhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ohbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int insert(Ohb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int insertSelective(Ohb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    List<Ohb> selectByExample(OhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    Ohb selectByPrimaryKey(String ohbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ohb record, @Param("example") OhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ohb record, @Param("example") OhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ohb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OHB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ohb record);
    
    // =============================
    // v2MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Ohb List
     * @param       reqEntity   (search criteria)
     * @return      Ohb List
     * @retval      List of Ohb Model Style
     * @attention
     * @note        Select Ohb List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<OhbModel> selectOhbInfoList(ReqGetOhbInfoListEntity reqEntity);
    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of Ohb List
     * @param     reqEntity     (search criteria)
     * @return    the total number of Ohb List
     * @retval    int Style
     * @attention
     * @note      Get the total number of Ohb List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetOhbInfoListEntity reqEntity);
}