package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.log.ReqGetOperationLogListEntity;
import net.muratec.mcs.model.OperationHistory;
import net.muratec.mcs.model.OperationHistoryExample;
import net.muratec.mcs.model.OperationHistoryModel;
import net.muratec.mcs.model.OperationLogModel;

public interface OperationHistoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    long countByExample(OperationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    int deleteByExample(OperationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    int insert(OperationHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    int insertSelective(OperationHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    List<OperationHistory> selectByExample(OperationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperationHistory record,
            @Param("example") OperationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATION_HISTORY
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperationHistory record, @Param("example") OperationHistoryExample example);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     getCount (Get the number of records of the Operation Log)function
     * @param     reqEntity request Entity from clien(Search condition)
     * @return    The total number of records in the list
     * @retval    Return in int format
     * @attention
     * @note      Get the number of records of the Operation Log information.
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     * MACS4#0109  HistSvr機能修正(GUI)(新規作成)                         T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetOperationLogListEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     selectList(Get of Operation Log information list)function
     * @param     reqEntity request Entity from client(Search condition)
     * @return    Operation log information list
     * @retval    Return the form of Operation Log information list
     * @attention
     * @note      Get of Operation Log information list
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     * MACS4#0109  HistSvr機能修正(GUI)(新規作成)                         T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
    List<OperationLogModel> selectList(ReqGetOperationLogListEntity reqEntity);

    //@formatter:off
    /**
     ******************************************************************************
     * @brief     insertTargetDate(Insert Operation History)function
     * @param     reqEntity Operation Information
     * @return
     * @retval
     * @attention
     * @note      Insert Operation History
     * ----------------------------------------------------------------------------
     * VER.        DESCRIPTION                                               AUTHOR
     * ----------------------------------------------------------------------------
     * MACS4#0109  HistSvr機能修正(GUI)(新規作成)                         T.Iga/CSC
     ******************************************************************************
     */
    //@formatter:on
    int insertTargetDate(OperationHistoryModel reqEntity);
    int insertTargetDatev2(OperationHistoryModel reqEntity);
}