package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.Piece;
import net.muratec.mcs.model.PieceExample;
import org.apache.ibatis.annotations.Param;

public interface PieceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    long countByExample(PieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int deleteByExample(PieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pieceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int insert(Piece record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int insertSelective(Piece record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    List<Piece> selectByExample(PieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    Piece selectByPrimaryKey(Integer pieceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Piece record, @Param("example") PieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Piece record, @Param("example") PieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Piece record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIECE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Piece record);
}