package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.PortConnPiece;
import net.muratec.mcs.model.PortConnPieceExample;
import net.muratec.mcs.model.PortConnPieceKey;
import org.apache.ibatis.annotations.Param;

public interface PortConnPieceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    long countByExample(PortConnPieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int deleteByExample(PortConnPieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PortConnPieceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int insert(PortConnPiece record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int insertSelective(PortConnPiece record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    List<PortConnPiece> selectByExample(PortConnPieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    PortConnPiece selectByPrimaryKey(PortConnPieceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PortConnPiece record, @Param("example") PortConnPieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PortConnPiece record, @Param("example") PortConnPieceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PortConnPiece record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PORT_CONN_PIECE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PortConnPiece record);
}