package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.entity.info.ReqGetRouteInfoListEntity;
import net.muratec.mcs.model.RouteList;
import net.muratec.mcs.model.RouteListExample;
import net.muratec.mcs.model.RouteListKey;
import net.muratec.mcs.model.RouteListModel;

public interface RouteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int countByExample(RouteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int deleteByExample(RouteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int deleteByPrimaryKey(RouteListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int insert(RouteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int insertSelective(RouteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    List<RouteList> selectByExample(RouteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    RouteList selectByPrimaryKey(RouteListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") RouteList record, @Param("example") RouteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int updateByExample(@Param("record") RouteList record, @Param("example") RouteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int updateByPrimaryKeySelective(RouteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTE_LIST
     *
     * @mbggenerated Wed Mar 25 18:38:09 CST 2020
     */
    int updateByPrimaryKey(RouteList record);
    
    // =============================
    // v2MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Route List
     * @param       reqEntity   (search criteria)
     * @return      Route List
     * @retval      List of Route Model Style
     * @attention
     * @note        Select Route List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<RouteListModel> selectRouteInfoList(ReqGetRouteInfoListEntity reqEntity);
    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of RouteList List
     * @param     reqEntity     (search criteria)
     * @return    the total number of Route List
     * @retval    int Style
     * @attention
     * @note      Get the total number of Route List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetRouteInfoListEntity reqEntity);
    
    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of RouteList List
     * @param     reqEntity     (search criteria)
     * @return    the total number of RouteList List
     * @retval    RouteList Style
     * @attention
     * @note      Select RouteList&tableNo For SelectBox
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
     //@formatter:on
     List<RouteList> selectTableNoListForSelectBox();
}