package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.ScreenMonitor;
import net.muratec.mcs.model.ScreenMonitorExample;
import net.muratec.mcs.model.ScreenMonitorKey;
import org.apache.ibatis.annotations.Param;

public interface ScreenMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    long countByExample(ScreenMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int deleteByExample(ScreenMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ScreenMonitorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int insert(ScreenMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int insertSelective(ScreenMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    List<ScreenMonitor> selectByExample(ScreenMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    ScreenMonitor selectByPrimaryKey(ScreenMonitorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ScreenMonitor record, @Param("example") ScreenMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ScreenMonitor record, @Param("example") ScreenMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScreenMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_MONITOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScreenMonitor record);
}