package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.ScreenColorMaster;
import net.muratec.mcs.model.ScreenColorMasterExample;
import org.apache.ibatis.annotations.Param;

public interface ScreenColorMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    long countByExample(ScreenColorMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int deleteByExample(ScreenColorMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String color);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int insert(ScreenColorMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int insertSelective(ScreenColorMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    List<ScreenColorMaster> selectByExample(ScreenColorMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    ScreenColorMaster selectByPrimaryKey(String color);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ScreenColorMaster record, @Param("example") ScreenColorMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ScreenColorMaster record, @Param("example") ScreenColorMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScreenColorMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCREEN_COLOR_MASTER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScreenColorMaster record);
    
    
    //20200106 DQY ADD START
    List<ScreenColorMaster> selectAllColor();
    //20200106 DQY ADD END

}