package net.muratec.mcs.mapper;

import java.util.List;
import net.muratec.mcs.model.SitemapTableConfig;
import net.muratec.mcs.model.SitemapTableConfigExample;
import org.apache.ibatis.annotations.Param;

public interface SitemapTableConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    long countByExample(SitemapTableConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    int deleteByExample(SitemapTableConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    int insert(SitemapTableConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    int insertSelective(SitemapTableConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    List<SitemapTableConfig> selectByExample(SitemapTableConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SitemapTableConfig record, @Param("example") SitemapTableConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITEMAP_TABLE_CONFIG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SitemapTableConfig record, @Param("example") SitemapTableConfigExample example);
}