package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.info.ReqGetStockerInfoEntity;
import net.muratec.mcs.model.StockerInfoModel;
import net.muratec.mcs.model.StockerZoneRlt;
import net.muratec.mcs.model.StockerZoneRltExample;
import net.muratec.mcs.model.StockerZoneRltKey;
import org.apache.ibatis.annotations.Param;

public interface StockerZoneRltMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int countByExample(StockerZoneRltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int deleteByExample(StockerZoneRltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int deleteByPrimaryKey(StockerZoneRltKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int insert(StockerZoneRlt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int insertSelective(StockerZoneRlt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    List<StockerZoneRlt> selectByExample(StockerZoneRltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    StockerZoneRlt selectByPrimaryKey(StockerZoneRltKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockerZoneRlt record, @Param("example") StockerZoneRltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int updateByExample(@Param("record") StockerZoneRlt record, @Param("example") StockerZoneRltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int updateByPrimaryKeySelective(StockerZoneRlt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCKER_ZONE_RLT
     *
     * @mbggenerated Mon Mar 09 13:26:43 CST 2020
     */
    int updateByPrimaryKey(StockerZoneRlt record);
    // STD APL 2020.03.12 董 天津村研  MCSV4　GUI開発  Ver2.0 Rev.000 
//    List<StockerInfoModel> selectStockerInfoList(ReqGetStockerInfoEntity record);
    List<StockerZoneRlt> selectStockerInfoList(ReqGetStockerInfoEntity record);
//    List<StockerZoneRlt> getCount(ReqGetStockerInfoEntity record);
    int getCount(ReqGetStockerInfoEntity record);
    // END APL 2020.03.12 董 天津村研  MCSV4　GUI開発  Ver2.0 Rev.000 

}