package net.muratec.mcs.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import net.muratec.mcs.model.StringMaster;
import net.muratec.mcs.model.StringMasterExample;
import net.muratec.mcs.model.StringMasterKey;

public interface StringMasterMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    long countByExample(StringMasterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int deleteByExample(StringMasterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int deleteByPrimaryKey(StringMasterKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int insert(StringMaster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int insertSelective(StringMaster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    List<StringMaster> selectByExample(StringMasterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    StringMaster selectByPrimaryKey(StringMasterKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StringMaster record, @Param("example") StringMasterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int updateByExample(@Param("record") StringMaster record, @Param("example") StringMasterExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StringMaster record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table STRING_MASTER
     * @mbg.generated
     */
    int updateByPrimaryKey(StringMaster record);
}
