package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.info.ReqGetTestCarrierListEntity;
import net.muratec.mcs.model.TestCarrierModel;
import net.muratec.mcs.model.TestCarrier;
import net.muratec.mcs.model.TestCarrierExample;
import org.apache.ibatis.annotations.Param;

public interface TestCarrierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int countByExample(TestCarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int deleteByExample(TestCarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int deleteByPrimaryKey(String testCarrierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int insert(TestCarrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int insertSelective(TestCarrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    List<TestCarrier> selectByExample(TestCarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    TestCarrier selectByPrimaryKey(String testCarrierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") TestCarrier record, @Param("example") TestCarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int updateByExample(@Param("record") TestCarrier record, @Param("example") TestCarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int updateByPrimaryKeySelective(TestCarrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_CARRIER
     *
     * @mbggenerated Thu Mar 12 17:20:28 CST 2020
     */
    int updateByPrimaryKey(TestCarrier record);
    
    // =============================
    // v2MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Test Carrier List
     * @param       reqEntity   (search criteria)
     * @return      Test Carrier List
     * @retval      List of Test Carrier Model Style
     * @attention
     * @note        Select Test Carrier List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<TestCarrierModel> selectTestCarrierList(ReqGetTestCarrierListEntity reqEntity);
    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of Test Carrier List
     * @param     reqEntity     (search criteria)
     * @return    the total number of Test Carrier List
     * @retval    int Style
     * @attention
     * @note      Get the total number of Test Carrier List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetTestCarrierListEntity reqEntity);
}