package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.hist.ReqGetJobStatisticsHistoryEntity;
import net.muratec.mcs.model.Port;
import net.muratec.mcs.model.StockerZoneRlt;
import net.muratec.mcs.model.TransferOpeLog;
import net.muratec.mcs.model.TransferOpeLogExample;
import net.muratec.mcs.model.TransferOpeLogKey;
import net.muratec.mcs.model.Tsc;

import org.apache.ibatis.annotations.Param;

public interface TransferOpeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int countByExample(TransferOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int deleteByExample(TransferOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int deleteByPrimaryKey(TransferOpeLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int insert(TransferOpeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int insertSelective(TransferOpeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    List<TransferOpeLog> selectByExample(TransferOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    TransferOpeLog selectByPrimaryKey(TransferOpeLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") TransferOpeLog record, @Param("example") TransferOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int updateByExample(@Param("record") TransferOpeLog record, @Param("example") TransferOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int updateByPrimaryKeySelective(TransferOpeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSFER_OPE_LOG
     *
     * @mbggenerated Thu Apr 09 15:17:50 CST 2020
     */
    int updateByPrimaryKey(TransferOpeLog record);
	// STD 2020.04.09 DONG  ADD 
    List<TransferOpeLog> selectHourJobByTscIdData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectHourJobBySrcLocData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectHourJobByDstLocData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectHourJobData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectDayJobByTscIdData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectDayJobBySrcLocData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectDayJobByDstLocData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<TransferOpeLog> selectDayJobData(ReqGetJobStatisticsHistoryEntity reqEntity);
    List<Tsc> selectTscNameList();
    List<StockerZoneRlt> selectZoneData(@Param("tscId") String tscId);
    List<Tsc> setTscName(@Param("tscId") String tscId);
    List<Port> selectPortData(@Param("tscId") String tscId);
    int getCountDayJobByTscIdData(ReqGetJobStatisticsHistoryEntity record);
    int getCountDayJobBySrcLocData(ReqGetJobStatisticsHistoryEntity record);
    int getCountDayJobByDstLocData(ReqGetJobStatisticsHistoryEntity record);
    int getCountDayJobData(ReqGetJobStatisticsHistoryEntity record);
    int getCountHourJobByTscIdData(ReqGetJobStatisticsHistoryEntity record);
    int getCountHourJobBySrcLocData(ReqGetJobStatisticsHistoryEntity record);
    int getCountHourJobByDstLocData(ReqGetJobStatisticsHistoryEntity record);
    int getCountHourJobData(ReqGetJobStatisticsHistoryEntity record);
    // END 2020.04.09 DONG  ADD
}