package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.hist.ReqGetStockerStatisticsHistEntity;
import net.muratec.mcs.entity.hist.ReqGetVehicleStatisticsHistoryEntity;
import net.muratec.mcs.model.StockerOpeLogModel;
import net.muratec.mcs.model.VehicleOpeLog;
import net.muratec.mcs.model.VehicleOpeLogExample;
import net.muratec.mcs.model.VehicleOpeLogKey;
import net.muratec.mcs.model.VehicleOpeLogModel;

import org.apache.ibatis.annotations.Param;

public interface VehicleOpeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int countByExample(VehicleOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int deleteByExample(VehicleOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int deleteByPrimaryKey(VehicleOpeLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int insert(VehicleOpeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int insertSelective(VehicleOpeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    List<VehicleOpeLog> selectByExample(VehicleOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    VehicleOpeLog selectByPrimaryKey(VehicleOpeLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") VehicleOpeLog record, @Param("example") VehicleOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int updateByExample(@Param("record") VehicleOpeLog record, @Param("example") VehicleOpeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int updateByPrimaryKeySelective(VehicleOpeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE_OPE_LOG
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    int updateByPrimaryKey(VehicleOpeLog record);
    
    // =============================
    // v2MCS Unique Function From Here
    // =============================
    List<VehicleOpeLogModel> selectVehicleStatisticsHistoryListByHour(ReqGetVehicleStatisticsHistoryEntity reqEntity);
    
    List<VehicleOpeLogModel> selectVehicleStatisticsHistoryListByDay(ReqGetVehicleStatisticsHistoryEntity reqEntity);
    
    String getDownTime(ReqGetVehicleStatisticsHistoryEntity reqEntity);
    int getCountByDay(ReqGetVehicleStatisticsHistoryEntity reqEntity);
    int getCountByHour(ReqGetVehicleStatisticsHistoryEntity reqEntity);
    int getVehicleCount(ReqGetVehicleStatisticsHistoryEntity reqEntity);
}