package net.muratec.mcs.mapper;

import java.util.List;

import net.muratec.mcs.entity.info.ReqGetVehicleInfoListEntity;
import net.muratec.mcs.model.VehicleInfo;
import net.muratec.mcs.model.VehicleInfoExample;
import net.muratec.mcs.model.VehicleInfoModel;

import org.apache.ibatis.annotations.Param;

public interface VehicleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    long countByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int deleteByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int insert(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int insertSelective(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    List<VehicleInfo> selectByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    VehicleInfo selectByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VehicleInfo record, @Param("example") VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VehicleInfo record, @Param("example") VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VEHICLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VehicleInfo record);
 // =============================
    // v2MCS Unique Function From Here
    // =============================
    //@formatter:off
    /**
     ******************************************************************************
     * @brief       Select Test Carrier List
     * @param       reqEntity   (search criteria)
     * @return      Test Carrier List
     * @retval      List of Test Carrier Model Style
     * @attention
     * @note        Select Test Carrier List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    List<VehicleInfoModel> selectVehicleInfoList(ReqGetVehicleInfoListEntity reqEntity);
    //@formatter:off
    /**
     ******************************************************************************
     * @brief     Get the total number of Test Carrier List
     * @param     reqEntity     (search criteria)
     * @return    the total number of Test Carrier List
     * @retval    int Style
     * @attention
     * @note      Get the total number of Test Carrier List that matches search criteria.
     * ----------------------------------------------------------------------------
     * DATE       VER.        DESCRIPTION                                    AUTHOR
     * ----------------------------------------------------------------------------
     ******************************************************************************
     */
    //@formatter:on
    int getCount(ReqGetVehicleInfoListEntity reqEntity);
}