package net.muratec.mcs.model;

public class Alarm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ALARM_ID
     *
     * @mbg.generated
     */
    private Long alarmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.SUB_CODE
     *
     * @mbg.generated
     */
    private Long subCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.TSC_ID
     *
     * @mbg.generated
     */
    private Integer tscId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.MACHINE_ID
     *
     * @mbg.generated
     */
    private String machineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.PIECE_ID
     *
     * @mbg.generated
     */
    private Integer pieceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.TSC_TYPE
     *
     * @mbg.generated
     */
    private String tscType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CLASS
     *
     * @mbg.generated
     */
    private Short alarmClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ALARM_TEXT
     *
     * @mbg.generated
     */
    private String alarmText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ALARM_LEVEL
     *
     * @mbg.generated
     */
    private Short alarmLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ALARM_REPORT
     *
     * @mbg.generated
     */
    private Short alarmReport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ERROR_UNIT
     *
     * @mbg.generated
     */
    private String errorUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ERROR_ID
     *
     * @mbg.generated
     */
    private String errorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.COMMAND_ID
     *
     * @mbg.generated
     */
    private String commandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.STOCKER_UNIT_ID
     *
     * @mbg.generated
     */
    private String stockerUnitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.STOCKER_UNIT_STATUS
     *
     * @mbg.generated
     */
    private Integer stockerUnitStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.RECOVERY_OPTION
     *
     * @mbg.generated
     */
    private String recoveryOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.SET_TIME
     *
     * @mbg.generated
     */
    private String setTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CLEARED_TIME
     *
     * @mbg.generated
     */
    private String clearedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.ALARM_LOC
     *
     * @mbg.generated
     */
    private String alarmLoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.VEHICLE_ID
     *
     * @mbg.generated
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CRANE_ID
     *
     * @mbg.generated
     */
    private String craneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CARRIER_ID
     *
     * @mbg.generated
     */
    private String carrierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CARRIER_ID2
     *
     * @mbg.generated
     */
    private String carrierId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CARRIER_ID3
     *
     * @mbg.generated
     */
    private String carrierId3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CARRIER_ID4
     *
     * @mbg.generated
     */
    private String carrierId4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.CARRIER_LOC
     *
     * @mbg.generated
     */
    private String carrierLoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.SOURCE
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.DEST
     *
     * @mbg.generated
     */
    private String dest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALARM.EQUIPMENT_INFO
     *
     * @mbg.generated
     */
    private String equipmentInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ALARM_ID
     *
     * @return the value of ALARM.ALARM_ID
     *
     * @mbg.generated
     */
    public Long getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ALARM_ID
     *
     * @param alarmId the value for ALARM.ALARM_ID
     *
     * @mbg.generated
     */
    public void setAlarmId(Long alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.SUB_CODE
     *
     * @return the value of ALARM.SUB_CODE
     *
     * @mbg.generated
     */
    public Long getSubCode() {
        return subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.SUB_CODE
     *
     * @param subCode the value for ALARM.SUB_CODE
     *
     * @mbg.generated
     */
    public void setSubCode(Long subCode) {
        this.subCode = subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.TSC_ID
     *
     * @return the value of ALARM.TSC_ID
     *
     * @mbg.generated
     */
    public Integer getTscId() {
        return tscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.TSC_ID
     *
     * @param tscId the value for ALARM.TSC_ID
     *
     * @mbg.generated
     */
    public void setTscId(Integer tscId) {
        this.tscId = tscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.MACHINE_ID
     *
     * @return the value of ALARM.MACHINE_ID
     *
     * @mbg.generated
     */
    public String getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.MACHINE_ID
     *
     * @param machineId the value for ALARM.MACHINE_ID
     *
     * @mbg.generated
     */
    public void setMachineId(String machineId) {
        this.machineId = machineId == null ? null : machineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.PIECE_ID
     *
     * @return the value of ALARM.PIECE_ID
     *
     * @mbg.generated
     */
    public Integer getPieceId() {
        return pieceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.PIECE_ID
     *
     * @param pieceId the value for ALARM.PIECE_ID
     *
     * @mbg.generated
     */
    public void setPieceId(Integer pieceId) {
        this.pieceId = pieceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.TSC_TYPE
     *
     * @return the value of ALARM.TSC_TYPE
     *
     * @mbg.generated
     */
    public String getTscType() {
        return tscType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.TSC_TYPE
     *
     * @param tscType the value for ALARM.TSC_TYPE
     *
     * @mbg.generated
     */
    public void setTscType(String tscType) {
        this.tscType = tscType == null ? null : tscType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CLASS
     *
     * @return the value of ALARM.CLASS
     *
     * @mbg.generated
     */
    public Short getAlarmClass() {
        return alarmClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CLASS
     *
     * @param class the value for ALARM.CLASS
     *
     * @mbg.generated
     */
    public void setAlarmClass(Short alarmClass) {
        this.alarmClass = alarmClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ALARM_TEXT
     *
     * @return the value of ALARM.ALARM_TEXT
     *
     * @mbg.generated
     */
    public String getAlarmText() {
        return alarmText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ALARM_TEXT
     *
     * @param alarmText the value for ALARM.ALARM_TEXT
     *
     * @mbg.generated
     */
    public void setAlarmText(String alarmText) {
        this.alarmText = alarmText == null ? null : alarmText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ALARM_LEVEL
     *
     * @return the value of ALARM.ALARM_LEVEL
     *
     * @mbg.generated
     */
    public Short getAlarmLevel() {
        return alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ALARM_LEVEL
     *
     * @param alarmLevel the value for ALARM.ALARM_LEVEL
     *
     * @mbg.generated
     */
    public void setAlarmLevel(Short alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ALARM_REPORT
     *
     * @return the value of ALARM.ALARM_REPORT
     *
     * @mbg.generated
     */
    public Short getAlarmReport() {
        return alarmReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ALARM_REPORT
     *
     * @param alarmReport the value for ALARM.ALARM_REPORT
     *
     * @mbg.generated
     */
    public void setAlarmReport(Short alarmReport) {
        this.alarmReport = alarmReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ERROR_UNIT
     *
     * @return the value of ALARM.ERROR_UNIT
     *
     * @mbg.generated
     */
    public String getErrorUnit() {
        return errorUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ERROR_UNIT
     *
     * @param errorUnit the value for ALARM.ERROR_UNIT
     *
     * @mbg.generated
     */
    public void setErrorUnit(String errorUnit) {
        this.errorUnit = errorUnit == null ? null : errorUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ERROR_ID
     *
     * @return the value of ALARM.ERROR_ID
     *
     * @mbg.generated
     */
    public String getErrorId() {
        return errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ERROR_ID
     *
     * @param errorId the value for ALARM.ERROR_ID
     *
     * @mbg.generated
     */
    public void setErrorId(String errorId) {
        this.errorId = errorId == null ? null : errorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.COMMAND_ID
     *
     * @return the value of ALARM.COMMAND_ID
     *
     * @mbg.generated
     */
    public String getCommandId() {
        return commandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.COMMAND_ID
     *
     * @param commandId the value for ALARM.COMMAND_ID
     *
     * @mbg.generated
     */
    public void setCommandId(String commandId) {
        this.commandId = commandId == null ? null : commandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.STOCKER_UNIT_ID
     *
     * @return the value of ALARM.STOCKER_UNIT_ID
     *
     * @mbg.generated
     */
    public String getStockerUnitId() {
        return stockerUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.STOCKER_UNIT_ID
     *
     * @param stockerUnitId the value for ALARM.STOCKER_UNIT_ID
     *
     * @mbg.generated
     */
    public void setStockerUnitId(String stockerUnitId) {
        this.stockerUnitId = stockerUnitId == null ? null : stockerUnitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.STOCKER_UNIT_STATUS
     *
     * @return the value of ALARM.STOCKER_UNIT_STATUS
     *
     * @mbg.generated
     */
    public Integer getStockerUnitStatus() {
        return stockerUnitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.STOCKER_UNIT_STATUS
     *
     * @param stockerUnitStatus the value for ALARM.STOCKER_UNIT_STATUS
     *
     * @mbg.generated
     */
    public void setStockerUnitStatus(Integer stockerUnitStatus) {
        this.stockerUnitStatus = stockerUnitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.RECOVERY_OPTION
     *
     * @return the value of ALARM.RECOVERY_OPTION
     *
     * @mbg.generated
     */
    public String getRecoveryOption() {
        return recoveryOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.RECOVERY_OPTION
     *
     * @param recoveryOption the value for ALARM.RECOVERY_OPTION
     *
     * @mbg.generated
     */
    public void setRecoveryOption(String recoveryOption) {
        this.recoveryOption = recoveryOption == null ? null : recoveryOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.SET_TIME
     *
     * @return the value of ALARM.SET_TIME
     *
     * @mbg.generated
     */
    public String getSetTime() {
        return setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.SET_TIME
     *
     * @param setTime the value for ALARM.SET_TIME
     *
     * @mbg.generated
     */
    public void setSetTime(String setTime) {
        this.setTime = setTime == null ? null : setTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CLEARED_TIME
     *
     * @return the value of ALARM.CLEARED_TIME
     *
     * @mbg.generated
     */
    public String getClearedTime() {
        return clearedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CLEARED_TIME
     *
     * @param clearedTime the value for ALARM.CLEARED_TIME
     *
     * @mbg.generated
     */
    public void setClearedTime(String clearedTime) {
        this.clearedTime = clearedTime == null ? null : clearedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.ALARM_LOC
     *
     * @return the value of ALARM.ALARM_LOC
     *
     * @mbg.generated
     */
    public String getAlarmLoc() {
        return alarmLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.ALARM_LOC
     *
     * @param alarmLoc the value for ALARM.ALARM_LOC
     *
     * @mbg.generated
     */
    public void setAlarmLoc(String alarmLoc) {
        this.alarmLoc = alarmLoc == null ? null : alarmLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.VEHICLE_ID
     *
     * @return the value of ALARM.VEHICLE_ID
     *
     * @mbg.generated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.VEHICLE_ID
     *
     * @param vehicleId the value for ALARM.VEHICLE_ID
     *
     * @mbg.generated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CRANE_ID
     *
     * @return the value of ALARM.CRANE_ID
     *
     * @mbg.generated
     */
    public String getCraneId() {
        return craneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CRANE_ID
     *
     * @param craneId the value for ALARM.CRANE_ID
     *
     * @mbg.generated
     */
    public void setCraneId(String craneId) {
        this.craneId = craneId == null ? null : craneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CARRIER_ID
     *
     * @return the value of ALARM.CARRIER_ID
     *
     * @mbg.generated
     */
    public String getCarrierId() {
        return carrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CARRIER_ID
     *
     * @param carrierId the value for ALARM.CARRIER_ID
     *
     * @mbg.generated
     */
    public void setCarrierId(String carrierId) {
        this.carrierId = carrierId == null ? null : carrierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CARRIER_ID2
     *
     * @return the value of ALARM.CARRIER_ID2
     *
     * @mbg.generated
     */
    public String getCarrierId2() {
        return carrierId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CARRIER_ID2
     *
     * @param carrierId2 the value for ALARM.CARRIER_ID2
     *
     * @mbg.generated
     */
    public void setCarrierId2(String carrierId2) {
        this.carrierId2 = carrierId2 == null ? null : carrierId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CARRIER_ID3
     *
     * @return the value of ALARM.CARRIER_ID3
     *
     * @mbg.generated
     */
    public String getCarrierId3() {
        return carrierId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CARRIER_ID3
     *
     * @param carrierId3 the value for ALARM.CARRIER_ID3
     *
     * @mbg.generated
     */
    public void setCarrierId3(String carrierId3) {
        this.carrierId3 = carrierId3 == null ? null : carrierId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CARRIER_ID4
     *
     * @return the value of ALARM.CARRIER_ID4
     *
     * @mbg.generated
     */
    public String getCarrierId4() {
        return carrierId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CARRIER_ID4
     *
     * @param carrierId4 the value for ALARM.CARRIER_ID4
     *
     * @mbg.generated
     */
    public void setCarrierId4(String carrierId4) {
        this.carrierId4 = carrierId4 == null ? null : carrierId4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.CARRIER_LOC
     *
     * @return the value of ALARM.CARRIER_LOC
     *
     * @mbg.generated
     */
    public String getCarrierLoc() {
        return carrierLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.CARRIER_LOC
     *
     * @param carrierLoc the value for ALARM.CARRIER_LOC
     *
     * @mbg.generated
     */
    public void setCarrierLoc(String carrierLoc) {
        this.carrierLoc = carrierLoc == null ? null : carrierLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.SOURCE
     *
     * @return the value of ALARM.SOURCE
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.SOURCE
     *
     * @param source the value for ALARM.SOURCE
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.DEST
     *
     * @return the value of ALARM.DEST
     *
     * @mbg.generated
     */
    public String getDest() {
        return dest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.DEST
     *
     * @param dest the value for ALARM.DEST
     *
     * @mbg.generated
     */
    public void setDest(String dest) {
        this.dest = dest == null ? null : dest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALARM.EQUIPMENT_INFO
     *
     * @return the value of ALARM.EQUIPMENT_INFO
     *
     * @mbg.generated
     */
    public String getEquipmentInfo() {
        return equipmentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALARM.EQUIPMENT_INFO
     *
     * @param equipmentInfo the value for ALARM.EQUIPMENT_INFO
     *
     * @mbg.generated
     */
    public void setEquipmentInfo(String equipmentInfo) {
        this.equipmentInfo = equipmentInfo == null ? null : equipmentInfo.trim();
    }
}