package net.muratec.mcs.model;

public class Dual {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DUAL.DUMMY
     *
     * @mbg.generated
     */
    private String dummy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DUAL.DUMMY
     *
     * @return the value of DUAL.DUMMY
     *
     * @mbg.generated
     */
    public String getDummy() {
        return dummy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DUAL.DUMMY
     *
     * @param dummy the value for DUAL.DUMMY
     *
     * @mbg.generated
     */
    public void setDummy(String dummy) {
        this.dummy = dummy;
    }
}