package net.muratec.mcs.model;

public class ErrorLogKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.TIME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.SEQ
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.ERROR_TYPE
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private Short errorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.ERROR_LEVEL
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private Integer errorLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.REQUESTER
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private String requester;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.WRITE_TIME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private String writeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.TIME
     *
     * @return the value of ERROR_LOG.TIME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.TIME
     *
     * @param time the value for ERROR_LOG.TIME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.SEQ
     *
     * @return the value of ERROR_LOG.SEQ
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.SEQ
     *
     * @param seq the value for ERROR_LOG.SEQ
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.ERROR_TYPE
     *
     * @return the value of ERROR_LOG.ERROR_TYPE
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public Short getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.ERROR_TYPE
     *
     * @param errorType the value for ERROR_LOG.ERROR_TYPE
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setErrorType(Short errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.ERROR_LEVEL
     *
     * @return the value of ERROR_LOG.ERROR_LEVEL
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public Integer getErrorLevel() {
        return errorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.ERROR_LEVEL
     *
     * @param errorLevel the value for ERROR_LOG.ERROR_LEVEL
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setErrorLevel(Integer errorLevel) {
        this.errorLevel = errorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.REQUESTER
     *
     * @return the value of ERROR_LOG.REQUESTER
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public String getRequester() {
        return requester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.REQUESTER
     *
     * @param requester the value for ERROR_LOG.REQUESTER
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setRequester(String requester) {
        this.requester = requester == null ? null : requester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.WRITE_TIME
     *
     * @return the value of ERROR_LOG.WRITE_TIME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public String getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.WRITE_TIME
     *
     * @param writeTime the value for ERROR_LOG.WRITE_TIME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setWriteTime(String writeTime) {
        this.writeTime = writeTime == null ? null : writeTime.trim();
    }
}