package net.muratec.mcs.model;

public class ErrorLog extends ErrorLogKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.SOURCE_NAME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.LINE_NO
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private Integer lineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.ERROR_CODE
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ERROR_LOG.DESCRIPTION
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.SOURCE_NAME
     *
     * @return the value of ERROR_LOG.SOURCE_NAME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.SOURCE_NAME
     *
     * @param sourceName the value for ERROR_LOG.SOURCE_NAME
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.LINE_NO
     *
     * @return the value of ERROR_LOG.LINE_NO
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public Integer getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.LINE_NO
     *
     * @param lineNo the value for ERROR_LOG.LINE_NO
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setLineNo(Integer lineNo) {
        this.lineNo = lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.ERROR_CODE
     *
     * @return the value of ERROR_LOG.ERROR_CODE
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.ERROR_CODE
     *
     * @param errorCode the value for ERROR_LOG.ERROR_CODE
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ERROR_LOG.DESCRIPTION
     *
     * @return the value of ERROR_LOG.DESCRIPTION
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ERROR_LOG.DESCRIPTION
     *
     * @param description the value for ERROR_LOG.DESCRIPTION
     *
     * @mbggenerated Wed Apr 15 15:04:18 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}