package net.muratec.mcs.model;

public class HandsOnTableConfigKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HANDS_ON_TABLE_CONFIG.SECTION
     * @mbg.generated
     */
    private String section;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HANDS_ON_TABLE_CONFIG.KEY
     * @mbg.generated
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HANDS_ON_TABLE_CONFIG.SECTION
     * @return  the value of HANDS_ON_TABLE_CONFIG.SECTION
     * @mbg.generated
     */
    public String getSection() {

        return section;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HANDS_ON_TABLE_CONFIG.SECTION
     * @param section  the value for HANDS_ON_TABLE_CONFIG.SECTION
     * @mbg.generated
     */
    public void setSection(String section) {

        this.section = section;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HANDS_ON_TABLE_CONFIG.KEY
     * @return  the value of HANDS_ON_TABLE_CONFIG.KEY
     * @mbg.generated
     */
    public String getKey() {

        return key;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HANDS_ON_TABLE_CONFIG.KEY
     * @param key  the value for HANDS_ON_TABLE_CONFIG.KEY
     * @mbg.generated
     */
    public void setKey(String key) {

        this.key = key;
    }
}
