package net.muratec.mcs.model;

public class MacroTransferLog extends MacroTransferLogKey {
	
	private String totalTime;
	private String tscId;
	private String loc;
	private String statusStr;
	private String cancelFlgStr;
	private String rerouteFlgStr;
	private String tscName;
	public String getTotalTime() {
		return totalTime;
	}
	public void setTotalTime(String totalTime) {
		this.totalTime = totalTime;
	}
	public String getTscId() {
		return tscId;
	}
	public void setTscId(String tscId) {
		this.tscId = tscId;
	}
	public String getLoc() {
		return loc;
	}
	public void setLoc(String loc) {
		this.loc = loc;
	}
	public String getStatusStr() {
		return statusStr;
	}
	public void setStatusStr(String statusStr) {
		this.statusStr = statusStr;
	}
	public String getCancelFlgStr() {
		return cancelFlgStr;
	}
	public void setCancelFlgStr(String cancelFlgStr) {
		this.cancelFlgStr = cancelFlgStr;
	}
	public String getRerouteFlgStr() {
		return rerouteFlgStr;
	}
	public void setRerouteFlgStr(String rerouteFlgStr) {
		this.rerouteFlgStr = rerouteFlgStr;
	}
	public String getTscName() {
		return tscName;
	}
	public void setTscName(String tscName) {
		this.tscName = tscName;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_HOST_COMMAND_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgHostCommandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_ORIGINATOR
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgOriginator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.COMMAND_TYPE
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String commandType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_PRIORITY
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short orgPriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_REPLACE
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short orgReplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_BATCH_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short orgBatchFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_SRC_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer orgSrcTscId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_SRC_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgSrcLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_SRC_ZONE_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgSrcZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_GROUP
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer orgDstTscId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID2
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer orgDstTscId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID3
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer orgDstTscId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID4
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer orgDstTscId4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID5
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer orgDstTscId5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_LOC2
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstLoc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_LOC3
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstLoc3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_LOC4
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstLoc4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_LOC5
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstLoc5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DST_ZONE_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDstZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_NEXT_DST
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgNextDst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_MANDATORY
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short orgMandatory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_ARRIVE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgArriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_DEPART_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgDepartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_RCV_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgRcvTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_START_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_CMP_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgCmpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_BATCH_SEQ
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short orgBatchSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_N2_PURGE_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short orgN2PurgeFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ORG_N2_PURGE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String orgN2PurgeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.REROUTE_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short rerouteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.REROUTE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer rerouteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.REROUTE_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String rerouteReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.CANCEL_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short cancelFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.CANCEL_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.CANCEL_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ALT_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short altFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ALT_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Integer altTscId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ALT_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String altLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ALT_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private String altReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACRO_TRANSFER_LOG.ER_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    private Short erFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_HOST_COMMAND_ID
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_HOST_COMMAND_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgHostCommandId() {
        return orgHostCommandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_HOST_COMMAND_ID
     *
     * @param orgHostCommandId the value for MACRO_TRANSFER_LOG.ORG_HOST_COMMAND_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgHostCommandId(String orgHostCommandId) {
        this.orgHostCommandId = orgHostCommandId == null ? null : orgHostCommandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_ORIGINATOR
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_ORIGINATOR
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgOriginator() {
        return orgOriginator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_ORIGINATOR
     *
     * @param orgOriginator the value for MACRO_TRANSFER_LOG.ORG_ORIGINATOR
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgOriginator(String orgOriginator) {
        this.orgOriginator = orgOriginator == null ? null : orgOriginator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.COMMAND_TYPE
     *
     * @return the value of MACRO_TRANSFER_LOG.COMMAND_TYPE
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getCommandType() {
        return commandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.COMMAND_TYPE
     *
     * @param commandType the value for MACRO_TRANSFER_LOG.COMMAND_TYPE
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setCommandType(String commandType) {
        this.commandType = commandType == null ? null : commandType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_PRIORITY
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_PRIORITY
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getOrgPriority() {
        return orgPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_PRIORITY
     *
     * @param orgPriority the value for MACRO_TRANSFER_LOG.ORG_PRIORITY
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgPriority(Short orgPriority) {
        this.orgPriority = orgPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_REPLACE
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_REPLACE
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getOrgReplace() {
        return orgReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_REPLACE
     *
     * @param orgReplace the value for MACRO_TRANSFER_LOG.ORG_REPLACE
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgReplace(Short orgReplace) {
        this.orgReplace = orgReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_BATCH_FLG
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_BATCH_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getOrgBatchFlg() {
        return orgBatchFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_BATCH_FLG
     *
     * @param orgBatchFlg the value for MACRO_TRANSFER_LOG.ORG_BATCH_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgBatchFlg(Short orgBatchFlg) {
        this.orgBatchFlg = orgBatchFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_SRC_TSC_ID
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_SRC_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getOrgSrcTscId() {
        return orgSrcTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_SRC_TSC_ID
     *
     * @param orgSrcTscId the value for MACRO_TRANSFER_LOG.ORG_SRC_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgSrcTscId(Integer orgSrcTscId) {
        this.orgSrcTscId = orgSrcTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_SRC_LOC
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_SRC_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgSrcLoc() {
        return orgSrcLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_SRC_LOC
     *
     * @param orgSrcLoc the value for MACRO_TRANSFER_LOG.ORG_SRC_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgSrcLoc(String orgSrcLoc) {
        this.orgSrcLoc = orgSrcLoc == null ? null : orgSrcLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_SRC_ZONE_ID
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_SRC_ZONE_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgSrcZoneId() {
        return orgSrcZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_SRC_ZONE_ID
     *
     * @param orgSrcZoneId the value for MACRO_TRANSFER_LOG.ORG_SRC_ZONE_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgSrcZoneId(String orgSrcZoneId) {
        this.orgSrcZoneId = orgSrcZoneId == null ? null : orgSrcZoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_GROUP
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_GROUP
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstGroup() {
        return orgDstGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_GROUP
     *
     * @param orgDstGroup the value for MACRO_TRANSFER_LOG.ORG_DST_GROUP
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstGroup(String orgDstGroup) {
        this.orgDstGroup = orgDstGroup == null ? null : orgDstGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getOrgDstTscId() {
        return orgDstTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID
     *
     * @param orgDstTscId the value for MACRO_TRANSFER_LOG.ORG_DST_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstTscId(Integer orgDstTscId) {
        this.orgDstTscId = orgDstTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID2
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_TSC_ID2
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getOrgDstTscId2() {
        return orgDstTscId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID2
     *
     * @param orgDstTscId2 the value for MACRO_TRANSFER_LOG.ORG_DST_TSC_ID2
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstTscId2(Integer orgDstTscId2) {
        this.orgDstTscId2 = orgDstTscId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID3
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_TSC_ID3
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getOrgDstTscId3() {
        return orgDstTscId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID3
     *
     * @param orgDstTscId3 the value for MACRO_TRANSFER_LOG.ORG_DST_TSC_ID3
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstTscId3(Integer orgDstTscId3) {
        this.orgDstTscId3 = orgDstTscId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID4
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_TSC_ID4
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getOrgDstTscId4() {
        return orgDstTscId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID4
     *
     * @param orgDstTscId4 the value for MACRO_TRANSFER_LOG.ORG_DST_TSC_ID4
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstTscId4(Integer orgDstTscId4) {
        this.orgDstTscId4 = orgDstTscId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID5
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_TSC_ID5
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getOrgDstTscId5() {
        return orgDstTscId5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_TSC_ID5
     *
     * @param orgDstTscId5 the value for MACRO_TRANSFER_LOG.ORG_DST_TSC_ID5
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstTscId5(Integer orgDstTscId5) {
        this.orgDstTscId5 = orgDstTscId5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstLoc() {
        return orgDstLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC
     *
     * @param orgDstLoc the value for MACRO_TRANSFER_LOG.ORG_DST_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstLoc(String orgDstLoc) {
        this.orgDstLoc = orgDstLoc == null ? null : orgDstLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC2
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_LOC2
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstLoc2() {
        return orgDstLoc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC2
     *
     * @param orgDstLoc2 the value for MACRO_TRANSFER_LOG.ORG_DST_LOC2
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstLoc2(String orgDstLoc2) {
        this.orgDstLoc2 = orgDstLoc2 == null ? null : orgDstLoc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC3
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_LOC3
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstLoc3() {
        return orgDstLoc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC3
     *
     * @param orgDstLoc3 the value for MACRO_TRANSFER_LOG.ORG_DST_LOC3
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstLoc3(String orgDstLoc3) {
        this.orgDstLoc3 = orgDstLoc3 == null ? null : orgDstLoc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC4
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_LOC4
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstLoc4() {
        return orgDstLoc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC4
     *
     * @param orgDstLoc4 the value for MACRO_TRANSFER_LOG.ORG_DST_LOC4
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstLoc4(String orgDstLoc4) {
        this.orgDstLoc4 = orgDstLoc4 == null ? null : orgDstLoc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC5
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_LOC5
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstLoc5() {
        return orgDstLoc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_LOC5
     *
     * @param orgDstLoc5 the value for MACRO_TRANSFER_LOG.ORG_DST_LOC5
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstLoc5(String orgDstLoc5) {
        this.orgDstLoc5 = orgDstLoc5 == null ? null : orgDstLoc5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DST_ZONE_ID
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DST_ZONE_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDstZoneId() {
        return orgDstZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DST_ZONE_ID
     *
     * @param orgDstZoneId the value for MACRO_TRANSFER_LOG.ORG_DST_ZONE_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDstZoneId(String orgDstZoneId) {
        this.orgDstZoneId = orgDstZoneId == null ? null : orgDstZoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_NEXT_DST
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_NEXT_DST
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgNextDst() {
        return orgNextDst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_NEXT_DST
     *
     * @param orgNextDst the value for MACRO_TRANSFER_LOG.ORG_NEXT_DST
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgNextDst(String orgNextDst) {
        this.orgNextDst = orgNextDst == null ? null : orgNextDst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_MANDATORY
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_MANDATORY
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getOrgMandatory() {
        return orgMandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_MANDATORY
     *
     * @param orgMandatory the value for MACRO_TRANSFER_LOG.ORG_MANDATORY
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgMandatory(Short orgMandatory) {
        this.orgMandatory = orgMandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_ARRIVE_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_ARRIVE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgArriveTime() {
        return orgArriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_ARRIVE_TIME
     *
     * @param orgArriveTime the value for MACRO_TRANSFER_LOG.ORG_ARRIVE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgArriveTime(String orgArriveTime) {
        this.orgArriveTime = orgArriveTime == null ? null : orgArriveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_DEPART_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_DEPART_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgDepartTime() {
        return orgDepartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_DEPART_TIME
     *
     * @param orgDepartTime the value for MACRO_TRANSFER_LOG.ORG_DEPART_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgDepartTime(String orgDepartTime) {
        this.orgDepartTime = orgDepartTime == null ? null : orgDepartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_RCV_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_RCV_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgRcvTime() {
        return orgRcvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_RCV_TIME
     *
     * @param orgRcvTime the value for MACRO_TRANSFER_LOG.ORG_RCV_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgRcvTime(String orgRcvTime) {
        this.orgRcvTime = orgRcvTime == null ? null : orgRcvTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_START_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_START_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgStartTime() {
        return orgStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_START_TIME
     *
     * @param orgStartTime the value for MACRO_TRANSFER_LOG.ORG_START_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgStartTime(String orgStartTime) {
        this.orgStartTime = orgStartTime == null ? null : orgStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_CMP_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_CMP_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgCmpTime() {
        return orgCmpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_CMP_TIME
     *
     * @param orgCmpTime the value for MACRO_TRANSFER_LOG.ORG_CMP_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgCmpTime(String orgCmpTime) {
        this.orgCmpTime = orgCmpTime == null ? null : orgCmpTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_BATCH_SEQ
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_BATCH_SEQ
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getOrgBatchSeq() {
        return orgBatchSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_BATCH_SEQ
     *
     * @param orgBatchSeq the value for MACRO_TRANSFER_LOG.ORG_BATCH_SEQ
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgBatchSeq(Short orgBatchSeq) {
        this.orgBatchSeq = orgBatchSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_N2_PURGE_FLG
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_N2_PURGE_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getOrgN2PurgeFlg() {
        return orgN2PurgeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_N2_PURGE_FLG
     *
     * @param orgN2PurgeFlg the value for MACRO_TRANSFER_LOG.ORG_N2_PURGE_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgN2PurgeFlg(Short orgN2PurgeFlg) {
        this.orgN2PurgeFlg = orgN2PurgeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ORG_N2_PURGE_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.ORG_N2_PURGE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getOrgN2PurgeTime() {
        return orgN2PurgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ORG_N2_PURGE_TIME
     *
     * @param orgN2PurgeTime the value for MACRO_TRANSFER_LOG.ORG_N2_PURGE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setOrgN2PurgeTime(String orgN2PurgeTime) {
        this.orgN2PurgeTime = orgN2PurgeTime == null ? null : orgN2PurgeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.REROUTE_FLG
     *
     * @return the value of MACRO_TRANSFER_LOG.REROUTE_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getRerouteFlg() {
        return rerouteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.REROUTE_FLG
     *
     * @param rerouteFlg the value for MACRO_TRANSFER_LOG.REROUTE_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setRerouteFlg(Short rerouteFlg) {
        this.rerouteFlg = rerouteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.REROUTE_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.REROUTE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getRerouteTime() {
        return rerouteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.REROUTE_TIME
     *
     * @param rerouteTime the value for MACRO_TRANSFER_LOG.REROUTE_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setRerouteTime(Integer rerouteTime) {
        this.rerouteTime = rerouteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.REROUTE_REASON
     *
     * @return the value of MACRO_TRANSFER_LOG.REROUTE_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getRerouteReason() {
        return rerouteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.REROUTE_REASON
     *
     * @param rerouteReason the value for MACRO_TRANSFER_LOG.REROUTE_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setRerouteReason(String rerouteReason) {
        this.rerouteReason = rerouteReason == null ? null : rerouteReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.CANCEL_FLG
     *
     * @return the value of MACRO_TRANSFER_LOG.CANCEL_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getCancelFlg() {
        return cancelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.CANCEL_FLG
     *
     * @param cancelFlg the value for MACRO_TRANSFER_LOG.CANCEL_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setCancelFlg(Short cancelFlg) {
        this.cancelFlg = cancelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.CANCEL_TIME
     *
     * @return the value of MACRO_TRANSFER_LOG.CANCEL_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.CANCEL_TIME
     *
     * @param cancelTime the value for MACRO_TRANSFER_LOG.CANCEL_TIME
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setCancelTime(Integer cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.CANCEL_REASON
     *
     * @return the value of MACRO_TRANSFER_LOG.CANCEL_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.CANCEL_REASON
     *
     * @param cancelReason the value for MACRO_TRANSFER_LOG.CANCEL_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ALT_FLG
     *
     * @return the value of MACRO_TRANSFER_LOG.ALT_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getAltFlg() {
        return altFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ALT_FLG
     *
     * @param altFlg the value for MACRO_TRANSFER_LOG.ALT_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setAltFlg(Short altFlg) {
        this.altFlg = altFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ALT_TSC_ID
     *
     * @return the value of MACRO_TRANSFER_LOG.ALT_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Integer getAltTscId() {
        return altTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ALT_TSC_ID
     *
     * @param altTscId the value for MACRO_TRANSFER_LOG.ALT_TSC_ID
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setAltTscId(Integer altTscId) {
        this.altTscId = altTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ALT_LOC
     *
     * @return the value of MACRO_TRANSFER_LOG.ALT_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getAltLoc() {
        return altLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ALT_LOC
     *
     * @param altLoc the value for MACRO_TRANSFER_LOG.ALT_LOC
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setAltLoc(String altLoc) {
        this.altLoc = altLoc == null ? null : altLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ALT_REASON
     *
     * @return the value of MACRO_TRANSFER_LOG.ALT_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public String getAltReason() {
        return altReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ALT_REASON
     *
     * @param altReason the value for MACRO_TRANSFER_LOG.ALT_REASON
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setAltReason(String altReason) {
        this.altReason = altReason == null ? null : altReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACRO_TRANSFER_LOG.ER_FLG
     *
     * @return the value of MACRO_TRANSFER_LOG.ER_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public Short getErFlg() {
        return erFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACRO_TRANSFER_LOG.ER_FLG
     *
     * @param erFlg the value for MACRO_TRANSFER_LOG.ER_FLG
     *
     * @mbggenerated Thu Mar 26 09:25:19 CST 2020
     */
    public void setErFlg(Short erFlg) {
        this.erFlg = erFlg;
    }
}