package net.muratec.mcs.model;

public class Ohb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.OHB_ID
     *
     * @mbg.generated
     */
    private String ohbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.OHB_NAME
     *
     * @mbg.generated
     */
    private String ohbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.OHB_ABBREVIATION
     *
     * @mbg.generated
     */
    private String ohbAbbreviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.OHB_MODE
     *
     * @mbg.generated
     */
    private String ohbMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.TOTAL_SHELVES
     *
     * @mbg.generated
     */
    private Integer totalShelves;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.EMPTY_SHELVES
     *
     * @mbg.generated
     */
    private Integer emptyShelves;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.L_EMPTY_SHELVES
     *
     * @mbg.generated
     */
    private Integer lEmptyShelves;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.HIGH_WATER_MARK
     *
     * @mbg.generated
     */
    private Integer highWaterMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.LOW_WATER_MARK
     *
     * @mbg.generated
     */
    private Integer lowWaterMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.MODE_SET_TIME
     *
     * @mbg.generated
     */
    private String modeSetTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.MODE_SET_SID
     *
     * @mbg.generated
     */
    private Integer modeSetSid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.MODE_SET_ORIGINATOR
     *
     * @mbg.generated
     */
    private String modeSetOriginator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.DISPLAY_FLG
     *
     * @mbg.generated
     */
    private Short displayFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OHB.SEARCH_FLG
     *
     * @mbg.generated
     */
    private Short searchFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.OHB_ID
     *
     * @return the value of OHB.OHB_ID
     *
     * @mbg.generated
     */
    public String getOhbId() {
        return ohbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.OHB_ID
     *
     * @param ohbId the value for OHB.OHB_ID
     *
     * @mbg.generated
     */
    public void setOhbId(String ohbId) {
        this.ohbId = ohbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.OHB_NAME
     *
     * @return the value of OHB.OHB_NAME
     *
     * @mbg.generated
     */
    public String getOhbName() {
        return ohbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.OHB_NAME
     *
     * @param ohbName the value for OHB.OHB_NAME
     *
     * @mbg.generated
     */
    public void setOhbName(String ohbName) {
        this.ohbName = ohbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.OHB_ABBREVIATION
     *
     * @return the value of OHB.OHB_ABBREVIATION
     *
     * @mbg.generated
     */
    public String getOhbAbbreviation() {
        return ohbAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.OHB_ABBREVIATION
     *
     * @param ohbAbbreviation the value for OHB.OHB_ABBREVIATION
     *
     * @mbg.generated
     */
    public void setOhbAbbreviation(String ohbAbbreviation) {
        this.ohbAbbreviation = ohbAbbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.OHB_MODE
     *
     * @return the value of OHB.OHB_MODE
     *
     * @mbg.generated
     */
    public String getOhbMode() {
        return ohbMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.OHB_MODE
     *
     * @param ohbMode the value for OHB.OHB_MODE
     *
     * @mbg.generated
     */
    public void setOhbMode(String ohbMode) {
        this.ohbMode = ohbMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.TOTAL_SHELVES
     *
     * @return the value of OHB.TOTAL_SHELVES
     *
     * @mbg.generated
     */
    public Integer getTotalShelves() {
        return totalShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.TOTAL_SHELVES
     *
     * @param totalShelves the value for OHB.TOTAL_SHELVES
     *
     * @mbg.generated
     */
    public void setTotalShelves(Integer totalShelves) {
        this.totalShelves = totalShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.EMPTY_SHELVES
     *
     * @return the value of OHB.EMPTY_SHELVES
     *
     * @mbg.generated
     */
    public Integer getEmptyShelves() {
        return emptyShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.EMPTY_SHELVES
     *
     * @param emptyShelves the value for OHB.EMPTY_SHELVES
     *
     * @mbg.generated
     */
    public void setEmptyShelves(Integer emptyShelves) {
        this.emptyShelves = emptyShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.L_EMPTY_SHELVES
     *
     * @return the value of OHB.L_EMPTY_SHELVES
     *
     * @mbg.generated
     */
    public Integer getlEmptyShelves() {
        return lEmptyShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.L_EMPTY_SHELVES
     *
     * @param lEmptyShelves the value for OHB.L_EMPTY_SHELVES
     *
     * @mbg.generated
     */
    public void setlEmptyShelves(Integer lEmptyShelves) {
        this.lEmptyShelves = lEmptyShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.HIGH_WATER_MARK
     *
     * @return the value of OHB.HIGH_WATER_MARK
     *
     * @mbg.generated
     */
    public Integer getHighWaterMark() {
        return highWaterMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.HIGH_WATER_MARK
     *
     * @param highWaterMark the value for OHB.HIGH_WATER_MARK
     *
     * @mbg.generated
     */
    public void setHighWaterMark(Integer highWaterMark) {
        this.highWaterMark = highWaterMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.LOW_WATER_MARK
     *
     * @return the value of OHB.LOW_WATER_MARK
     *
     * @mbg.generated
     */
    public Integer getLowWaterMark() {
        return lowWaterMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.LOW_WATER_MARK
     *
     * @param lowWaterMark the value for OHB.LOW_WATER_MARK
     *
     * @mbg.generated
     */
    public void setLowWaterMark(Integer lowWaterMark) {
        this.lowWaterMark = lowWaterMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.MODE_SET_TIME
     *
     * @return the value of OHB.MODE_SET_TIME
     *
     * @mbg.generated
     */
    public String getModeSetTime() {
        return modeSetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.MODE_SET_TIME
     *
     * @param modeSetTime the value for OHB.MODE_SET_TIME
     *
     * @mbg.generated
     */
    public void setModeSetTime(String modeSetTime) {
        this.modeSetTime = modeSetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.MODE_SET_SID
     *
     * @return the value of OHB.MODE_SET_SID
     *
     * @mbg.generated
     */
    public Integer getModeSetSid() {
        return modeSetSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.MODE_SET_SID
     *
     * @param modeSetSid the value for OHB.MODE_SET_SID
     *
     * @mbg.generated
     */
    public void setModeSetSid(Integer modeSetSid) {
        this.modeSetSid = modeSetSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.MODE_SET_ORIGINATOR
     *
     * @return the value of OHB.MODE_SET_ORIGINATOR
     *
     * @mbg.generated
     */
    public String getModeSetOriginator() {
        return modeSetOriginator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.MODE_SET_ORIGINATOR
     *
     * @param modeSetOriginator the value for OHB.MODE_SET_ORIGINATOR
     *
     * @mbg.generated
     */
    public void setModeSetOriginator(String modeSetOriginator) {
        this.modeSetOriginator = modeSetOriginator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.DISPLAY_FLG
     *
     * @return the value of OHB.DISPLAY_FLG
     *
     * @mbg.generated
     */
    public Short getDisplayFlg() {
        return displayFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.DISPLAY_FLG
     *
     * @param displayFlg the value for OHB.DISPLAY_FLG
     *
     * @mbg.generated
     */
    public void setDisplayFlg(Short displayFlg) {
        this.displayFlg = displayFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OHB.SEARCH_FLG
     *
     * @return the value of OHB.SEARCH_FLG
     *
     * @mbg.generated
     */
    public Short getSearchFlg() {
        return searchFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OHB.SEARCH_FLG
     *
     * @param searchFlg the value for OHB.SEARCH_FLG
     *
     * @mbg.generated
     */
    public void setSearchFlg(Short searchFlg) {
        this.searchFlg = searchFlg;
    }
}