package net.muratec.mcs.model;

public class OhbifAreaIfohb {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column OHBIF_AREA_IFOHB.IFOHB_GRP
     * @mbg.generated
     */
    private String ifohbGrp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column OHBIF_AREA_IFOHB.PRIORITY
     * @mbg.generated
     */
    private Short priority;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column OHBIF_AREA_IFOHB.AREA_NAME
     * @mbg.generated
     */
    private String areaName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column OHBIF_AREA_IFOHB.IO_MODE
     * @mbg.generated
     */
    private Short ioMode;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column OHBIF_AREA_IFOHB.IFOHB_GRP
     * @return  the value of OHBIF_AREA_IFOHB.IFOHB_GRP
     * @mbg.generated
     */
    public String getIfohbGrp() {
        return ifohbGrp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column OHBIF_AREA_IFOHB.IFOHB_GRP
     * @param ifohbGrp  the value for OHBIF_AREA_IFOHB.IFOHB_GRP
     * @mbg.generated
     */
    public void setIfohbGrp(String ifohbGrp) {
        this.ifohbGrp = ifohbGrp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column OHBIF_AREA_IFOHB.PRIORITY
     * @return  the value of OHBIF_AREA_IFOHB.PRIORITY
     * @mbg.generated
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column OHBIF_AREA_IFOHB.PRIORITY
     * @param priority  the value for OHBIF_AREA_IFOHB.PRIORITY
     * @mbg.generated
     */
    public void setPriority(Short priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column OHBIF_AREA_IFOHB.AREA_NAME
     * @return  the value of OHBIF_AREA_IFOHB.AREA_NAME
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column OHBIF_AREA_IFOHB.AREA_NAME
     * @param areaName  the value for OHBIF_AREA_IFOHB.AREA_NAME
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column OHBIF_AREA_IFOHB.IO_MODE
     * @return  the value of OHBIF_AREA_IFOHB.IO_MODE
     * @mbg.generated
     */
    public Short getIoMode() {
        return ioMode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column OHBIF_AREA_IFOHB.IO_MODE
     * @param ioMode  the value for OHBIF_AREA_IFOHB.IO_MODE
     * @mbg.generated
     */
    public void setIoMode(Short ioMode) {
        this.ioMode = ioMode;
    }
}