package net.muratec.mcs.model;

public class OhbPortRltKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column OHB_PORT_RLT.OHB_ID
     * @mbg.generated
     */
    private String ohbId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column OHB_PORT_RLT.PORT_ID
     * @mbg.generated
     */
    private String portId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column OHB_PORT_RLT.OHB_ID
     * @return  the value of OHB_PORT_RLT.OHB_ID
     * @mbg.generated
     */
    public String getOhbId() {

        return ohbId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column OHB_PORT_RLT.OHB_ID
     * @param ohbId  the value for OHB_PORT_RLT.OHB_ID
     * @mbg.generated
     */
    public void setOhbId(String ohbId) {

        this.ohbId = ohbId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column OHB_PORT_RLT.PORT_ID
     * @return  the value of OHB_PORT_RLT.PORT_ID
     * @mbg.generated
     */
    public String getPortId() {

        return portId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column OHB_PORT_RLT.PORT_ID
     * @param portId  the value for OHB_PORT_RLT.PORT_ID
     * @mbg.generated
     */
    public void setPortId(String portId) {

        this.portId = portId;
    }
}
