package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;
import java.sql.Timestamp;

public class PortStateExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public PortStateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPortIdIsNull() {

            addCriterion("PORT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPortIdIsNotNull() {

            addCriterion("PORT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPortIdEqualTo(String value) {

            addCriterion("PORT_ID =", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotEqualTo(String value) {

            addCriterion("PORT_ID <>", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdGreaterThan(String value) {

            addCriterion("PORT_ID >", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdGreaterThanOrEqualTo(String value) {

            addCriterion("PORT_ID >=", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdLessThan(String value) {

            addCriterion("PORT_ID <", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdLessThanOrEqualTo(String value) {

            addCriterion("PORT_ID <=", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdLike(String value) {

            addCriterion("PORT_ID like", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotLike(String value) {

            addCriterion("PORT_ID not like", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdIn(List<String> values) {

            addCriterion("PORT_ID in", values, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotIn(List<String> values) {

            addCriterion("PORT_ID not in", values, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdBetween(String value1, String value2) {

            addCriterion("PORT_ID between", value1, value2, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotBetween(String value1, String value2) {

            addCriterion("PORT_ID not between", value1, value2, "portId");
            return (Criteria) this;
        }

        public Criteria andPortLStateIsNull() {

            addCriterion("PORT_L_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPortLStateIsNotNull() {

            addCriterion("PORT_L_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPortLStateEqualTo(Short value) {

            addCriterion("PORT_L_STATE =", value, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateNotEqualTo(Short value) {

            addCriterion("PORT_L_STATE <>", value, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateGreaterThan(Short value) {

            addCriterion("PORT_L_STATE >", value, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateGreaterThanOrEqualTo(Short value) {

            addCriterion("PORT_L_STATE >=", value, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateLessThan(Short value) {

            addCriterion("PORT_L_STATE <", value, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateLessThanOrEqualTo(Short value) {

            addCriterion("PORT_L_STATE <=", value, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateIn(List<Short> values) {

            addCriterion("PORT_L_STATE in", values, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateNotIn(List<Short> values) {

            addCriterion("PORT_L_STATE not in", values, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateBetween(Short value1, Short value2) {

            addCriterion("PORT_L_STATE between", value1, value2, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateNotBetween(Short value1, Short value2) {

            addCriterion("PORT_L_STATE not between", value1, value2, "portLState");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeIsNull() {

            addCriterion("PORT_L_STATE_SET_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeIsNotNull() {

            addCriterion("PORT_L_STATE_SET_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeEqualTo(Timestamp value) {

            addCriterion("PORT_L_STATE_SET_TIME =", value, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeNotEqualTo(Timestamp value) {

            addCriterion("PORT_L_STATE_SET_TIME <>", value, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeGreaterThan(Timestamp value) {

            addCriterion("PORT_L_STATE_SET_TIME >", value, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeGreaterThanOrEqualTo(Timestamp value) {

            addCriterion("PORT_L_STATE_SET_TIME >=", value, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeLessThan(Timestamp value) {

            addCriterion("PORT_L_STATE_SET_TIME <", value, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeLessThanOrEqualTo(Timestamp value) {

            addCriterion("PORT_L_STATE_SET_TIME <=", value, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeIn(List<Timestamp> values) {

            addCriterion("PORT_L_STATE_SET_TIME in", values, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeNotIn(List<Timestamp> values) {

            addCriterion("PORT_L_STATE_SET_TIME not in", values, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeBetween(Timestamp value1, Timestamp value2) {

            addCriterion("PORT_L_STATE_SET_TIME between", value1, value2, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetTimeNotBetween(Timestamp value1, Timestamp value2) {

            addCriterion("PORT_L_STATE_SET_TIME not between", value1, value2, "portLStateSetTime");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorIsNull() {

            addCriterion("PORT_L_STATE_SET_AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorIsNotNull() {

            addCriterion("PORT_L_STATE_SET_AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorEqualTo(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR =", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorNotEqualTo(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR <>", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorGreaterThan(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR >", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorGreaterThanOrEqualTo(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR >=", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorLessThan(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR <", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorLessThanOrEqualTo(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR <=", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorLike(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR like", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorNotLike(String value) {

            addCriterion("PORT_L_STATE_SET_AUTHOR not like", value, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorIn(List<String> values) {

            addCriterion("PORT_L_STATE_SET_AUTHOR in", values, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorNotIn(List<String> values) {

            addCriterion("PORT_L_STATE_SET_AUTHOR not in", values, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorBetween(String value1, String value2) {

            addCriterion("PORT_L_STATE_SET_AUTHOR between", value1, value2, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortLStateSetAuthorNotBetween(String value1, String value2) {

            addCriterion("PORT_L_STATE_SET_AUTHOR not between", value1, value2, "portLStateSetAuthor");
            return (Criteria) this;
        }

        public Criteria andPortAvailIsNull() {

            addCriterion("PORT_AVAIL is null");
            return (Criteria) this;
        }

        public Criteria andPortAvailIsNotNull() {

            addCriterion("PORT_AVAIL is not null");
            return (Criteria) this;
        }

        public Criteria andPortAvailEqualTo(Short value) {

            addCriterion("PORT_AVAIL =", value, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailNotEqualTo(Short value) {

            addCriterion("PORT_AVAIL <>", value, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailGreaterThan(Short value) {

            addCriterion("PORT_AVAIL >", value, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailGreaterThanOrEqualTo(Short value) {

            addCriterion("PORT_AVAIL >=", value, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailLessThan(Short value) {

            addCriterion("PORT_AVAIL <", value, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailLessThanOrEqualTo(Short value) {

            addCriterion("PORT_AVAIL <=", value, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailIn(List<Short> values) {

            addCriterion("PORT_AVAIL in", values, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailNotIn(List<Short> values) {

            addCriterion("PORT_AVAIL not in", values, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailBetween(Short value1, Short value2) {

            addCriterion("PORT_AVAIL between", value1, value2, "portAvail");
            return (Criteria) this;
        }

        public Criteria andPortAvailNotBetween(Short value1, Short value2) {

            addCriterion("PORT_AVAIL not between", value1, value2, "portAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailIsNull() {

            addCriterion("IBSEM_AVAIL is null");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailIsNotNull() {

            addCriterion("IBSEM_AVAIL is not null");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailEqualTo(Short value) {

            addCriterion("IBSEM_AVAIL =", value, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailNotEqualTo(Short value) {

            addCriterion("IBSEM_AVAIL <>", value, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailGreaterThan(Short value) {

            addCriterion("IBSEM_AVAIL >", value, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailGreaterThanOrEqualTo(Short value) {

            addCriterion("IBSEM_AVAIL >=", value, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailLessThan(Short value) {

            addCriterion("IBSEM_AVAIL <", value, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailLessThanOrEqualTo(Short value) {

            addCriterion("IBSEM_AVAIL <=", value, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailIn(List<Short> values) {

            addCriterion("IBSEM_AVAIL in", values, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailNotIn(List<Short> values) {

            addCriterion("IBSEM_AVAIL not in", values, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailBetween(Short value1, Short value2) {

            addCriterion("IBSEM_AVAIL between", value1, value2, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIbsemAvailNotBetween(Short value1, Short value2) {

            addCriterion("IBSEM_AVAIL not between", value1, value2, "ibsemAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailIsNull() {

            addCriterion("IDRW_AVAIL is null");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailIsNotNull() {

            addCriterion("IDRW_AVAIL is not null");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailEqualTo(Short value) {

            addCriterion("IDRW_AVAIL =", value, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailNotEqualTo(Short value) {

            addCriterion("IDRW_AVAIL <>", value, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailGreaterThan(Short value) {

            addCriterion("IDRW_AVAIL >", value, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailGreaterThanOrEqualTo(Short value) {

            addCriterion("IDRW_AVAIL >=", value, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailLessThan(Short value) {

            addCriterion("IDRW_AVAIL <", value, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailLessThanOrEqualTo(Short value) {

            addCriterion("IDRW_AVAIL <=", value, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailIn(List<Short> values) {

            addCriterion("IDRW_AVAIL in", values, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailNotIn(List<Short> values) {

            addCriterion("IDRW_AVAIL not in", values, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailBetween(Short value1, Short value2) {

            addCriterion("IDRW_AVAIL between", value1, value2, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdrwAvailNotBetween(Short value1, Short value2) {

            addCriterion("IDRW_AVAIL not between", value1, value2, "idrwAvail");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountIsNull() {

            addCriterion("ID_ERROR_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountIsNotNull() {

            addCriterion("ID_ERROR_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountEqualTo(Short value) {

            addCriterion("ID_ERROR_COUNT =", value, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountNotEqualTo(Short value) {

            addCriterion("ID_ERROR_COUNT <>", value, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountGreaterThan(Short value) {

            addCriterion("ID_ERROR_COUNT >", value, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountGreaterThanOrEqualTo(Short value) {

            addCriterion("ID_ERROR_COUNT >=", value, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountLessThan(Short value) {

            addCriterion("ID_ERROR_COUNT <", value, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountLessThanOrEqualTo(Short value) {

            addCriterion("ID_ERROR_COUNT <=", value, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountIn(List<Short> values) {

            addCriterion("ID_ERROR_COUNT in", values, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountNotIn(List<Short> values) {

            addCriterion("ID_ERROR_COUNT not in", values, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountBetween(Short value1, Short value2) {

            addCriterion("ID_ERROR_COUNT between", value1, value2, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andIdErrorCountNotBetween(Short value1, Short value2) {

            addCriterion("ID_ERROR_COUNT not between", value1, value2, "idErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountIsNull() {

            addCriterion("DPL_ERROR_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountIsNotNull() {

            addCriterion("DPL_ERROR_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountEqualTo(Short value) {

            addCriterion("DPL_ERROR_COUNT =", value, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountNotEqualTo(Short value) {

            addCriterion("DPL_ERROR_COUNT <>", value, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountGreaterThan(Short value) {

            addCriterion("DPL_ERROR_COUNT >", value, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountGreaterThanOrEqualTo(Short value) {

            addCriterion("DPL_ERROR_COUNT >=", value, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountLessThan(Short value) {

            addCriterion("DPL_ERROR_COUNT <", value, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountLessThanOrEqualTo(Short value) {

            addCriterion("DPL_ERROR_COUNT <=", value, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountIn(List<Short> values) {

            addCriterion("DPL_ERROR_COUNT in", values, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountNotIn(List<Short> values) {

            addCriterion("DPL_ERROR_COUNT not in", values, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountBetween(Short value1, Short value2) {

            addCriterion("DPL_ERROR_COUNT between", value1, value2, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andDplErrorCountNotBetween(Short value1, Short value2) {

            addCriterion("DPL_ERROR_COUNT not between", value1, value2, "dplErrorCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountIsNull() {

            addCriterion("INCORRECT_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountIsNotNull() {

            addCriterion("INCORRECT_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountEqualTo(Short value) {

            addCriterion("INCORRECT_COUNT =", value, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountNotEqualTo(Short value) {

            addCriterion("INCORRECT_COUNT <>", value, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountGreaterThan(Short value) {

            addCriterion("INCORRECT_COUNT >", value, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountGreaterThanOrEqualTo(Short value) {

            addCriterion("INCORRECT_COUNT >=", value, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountLessThan(Short value) {

            addCriterion("INCORRECT_COUNT <", value, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountLessThanOrEqualTo(Short value) {

            addCriterion("INCORRECT_COUNT <=", value, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountIn(List<Short> values) {

            addCriterion("INCORRECT_COUNT in", values, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountNotIn(List<Short> values) {

            addCriterion("INCORRECT_COUNT not in", values, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountBetween(Short value1, Short value2) {

            addCriterion("INCORRECT_COUNT between", value1, value2, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andIncorrectCountNotBetween(Short value1, Short value2) {

            addCriterion("INCORRECT_COUNT not between", value1, value2, "incorrectCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountIsNull() {

            addCriterion("E84_ERROR_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountIsNotNull() {

            addCriterion("E84_ERROR_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountEqualTo(Short value) {

            addCriterion("E84_ERROR_COUNT =", value, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountNotEqualTo(Short value) {

            addCriterion("E84_ERROR_COUNT <>", value, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountGreaterThan(Short value) {

            addCriterion("E84_ERROR_COUNT >", value, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountGreaterThanOrEqualTo(Short value) {

            addCriterion("E84_ERROR_COUNT >=", value, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountLessThan(Short value) {

            addCriterion("E84_ERROR_COUNT <", value, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountLessThanOrEqualTo(Short value) {

            addCriterion("E84_ERROR_COUNT <=", value, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountIn(List<Short> values) {

            addCriterion("E84_ERROR_COUNT in", values, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountNotIn(List<Short> values) {

            addCriterion("E84_ERROR_COUNT not in", values, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountBetween(Short value1, Short value2) {

            addCriterion("E84_ERROR_COUNT between", value1, value2, "e84ErrorCount");
            return (Criteria) this;
        }

        public Criteria andE84ErrorCountNotBetween(Short value1, Short value2) {

            addCriterion("E84_ERROR_COUNT not between", value1, value2, "e84ErrorCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table PORT_STATE
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table PORT_STATE
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 15:13:24 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
