package net.muratec.mcs.model;

public class PortConnKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PORT_CONN.CONN_FROM_TSC_ID
     *
     * @mbg.generated
     */
    private Integer connFromTscId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PORT_CONN.CONN_TO_TSC_ID
     *
     * @mbg.generated
     */
    private Integer connToTscId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PORT_CONN.PORT_ID
     *
     * @mbg.generated
     */
    private String portId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PORT_CONN.CONN_FROM_TSC_ID
     *
     * @return the value of PORT_CONN.CONN_FROM_TSC_ID
     *
     * @mbg.generated
     */
    public Integer getConnFromTscId() {
        return connFromTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PORT_CONN.CONN_FROM_TSC_ID
     *
     * @param connFromTscId the value for PORT_CONN.CONN_FROM_TSC_ID
     *
     * @mbg.generated
     */
    public void setConnFromTscId(Integer connFromTscId) {
        this.connFromTscId = connFromTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PORT_CONN.CONN_TO_TSC_ID
     *
     * @return the value of PORT_CONN.CONN_TO_TSC_ID
     *
     * @mbg.generated
     */
    public Integer getConnToTscId() {
        return connToTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PORT_CONN.CONN_TO_TSC_ID
     *
     * @param connToTscId the value for PORT_CONN.CONN_TO_TSC_ID
     *
     * @mbg.generated
     */
    public void setConnToTscId(Integer connToTscId) {
        this.connToTscId = connToTscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PORT_CONN.PORT_ID
     *
     * @return the value of PORT_CONN.PORT_ID
     *
     * @mbg.generated
     */
    public String getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PORT_CONN.PORT_ID
     *
     * @param portId the value for PORT_CONN.PORT_ID
     *
     * @mbg.generated
     */
    public void setPortId(String portId) {
        this.portId = portId;
    }
}