package net.muratec.mcs.model;

public class PortConnPiece extends PortConnPieceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PORT_CONN_PIECE.BUFFER
     *
     * @mbg.generated
     */
    private Short buffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PORT_CONN_PIECE.USE_TIME
     *
     * @mbg.generated
     */
    private String useTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PORT_CONN_PIECE.CONN_PRIORITY
     *
     * @mbg.generated
     */
    private Short connPriority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PORT_CONN_PIECE.BUFFER
     *
     * @return the value of PORT_CONN_PIECE.BUFFER
     *
     * @mbg.generated
     */
    public Short getBuffer() {
        return buffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PORT_CONN_PIECE.BUFFER
     *
     * @param buffer the value for PORT_CONN_PIECE.BUFFER
     *
     * @mbg.generated
     */
    public void setBuffer(Short buffer) {
        this.buffer = buffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PORT_CONN_PIECE.USE_TIME
     *
     * @return the value of PORT_CONN_PIECE.USE_TIME
     *
     * @mbg.generated
     */
    public String getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PORT_CONN_PIECE.USE_TIME
     *
     * @param useTime the value for PORT_CONN_PIECE.USE_TIME
     *
     * @mbg.generated
     */
    public void setUseTime(String useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PORT_CONN_PIECE.CONN_PRIORITY
     *
     * @return the value of PORT_CONN_PIECE.CONN_PRIORITY
     *
     * @mbg.generated
     */
    public Short getConnPriority() {
        return connPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PORT_CONN_PIECE.CONN_PRIORITY
     *
     * @param connPriority the value for PORT_CONN_PIECE.CONN_PRIORITY
     *
     * @mbg.generated
     */
    public void setConnPriority(Short connPriority) {
        this.connPriority = connPriority;
    }
}