package net.muratec.mcs.model;

import java.util.ArrayList;
import java.util.List;

public class ProcessExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table PROCESS
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table PROCESS
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table PROCESS
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public ProcessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {

        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public String getOrderByClause() {

        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {

        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public boolean isDistinct() {

        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {

        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public void or(Criteria criteria) {

        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public Criteria or() {

        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public Criteria createCriteria() {

        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {

        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table PROCESS
     * @mbg.generated
     */
    public void clear() {

        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table PROCESS
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {

            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {

            return criteria;
        }

        public List<Criterion> getCriteria() {

            return criteria;
        }

        protected void addCriterion(String condition) {

            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {

            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {

            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemIdIsNull() {

            addCriterion("SYSTEM_ID is null");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNotNull() {

            addCriterion("SYSTEM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIdEqualTo(Integer value) {

            addCriterion("SYSTEM_ID =", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotEqualTo(Integer value) {

            addCriterion("SYSTEM_ID <>", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThan(Integer value) {

            addCriterion("SYSTEM_ID >", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThanOrEqualTo(Integer value) {

            addCriterion("SYSTEM_ID >=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThan(Integer value) {

            addCriterion("SYSTEM_ID <", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThanOrEqualTo(Integer value) {

            addCriterion("SYSTEM_ID <=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdIn(List<Integer> values) {

            addCriterion("SYSTEM_ID in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotIn(List<Integer> values) {

            addCriterion("SYSTEM_ID not in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdBetween(Integer value1, Integer value2) {

            addCriterion("SYSTEM_ID between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotBetween(Integer value1, Integer value2) {

            addCriterion("SYSTEM_ID not between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNull() {

            addCriterion("SERVICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {

            addCriterion("SERVICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(String value) {

            addCriterion("SERVICE_ID =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(String value) {

            addCriterion("SERVICE_ID <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(String value) {

            addCriterion("SERVICE_ID >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(String value) {

            addCriterion("SERVICE_ID >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(String value) {

            addCriterion("SERVICE_ID <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(String value) {

            addCriterion("SERVICE_ID <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLike(String value) {

            addCriterion("SERVICE_ID like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotLike(String value) {

            addCriterion("SERVICE_ID not like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<String> values) {

            addCriterion("SERVICE_ID in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<String> values) {

            addCriterion("SERVICE_ID not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(String value1, String value2) {

            addCriterion("SERVICE_ID between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(String value1, String value2) {

            addCriterion("SERVICE_ID not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {

            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {

            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {

            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {

            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {

            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {

            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {

            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {

            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {

            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {

            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {

            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {

            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {

            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {

            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andProcCategoryIsNull() {
            addCriterion("PROC_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andProcCategoryIsNotNull() {
            addCriterion("PROC_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andProcCategoryEqualTo(Short value) {
            addCriterion("PROC_CATEGORY =", value, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryNotEqualTo(Short value) {
            addCriterion("PROC_CATEGORY <>", value, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryGreaterThan(Short value) {
            addCriterion("PROC_CATEGORY >", value, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryGreaterThanOrEqualTo(Short value) {
            addCriterion("PROC_CATEGORY >=", value, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryLessThan(Short value) {
            addCriterion("PROC_CATEGORY <", value, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryLessThanOrEqualTo(Short value) {
            addCriterion("PROC_CATEGORY <=", value, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryIn(List<Short> values) {
            addCriterion("PROC_CATEGORY in", values, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryNotIn(List<Short> values) {
            addCriterion("PROC_CATEGORY not in", values, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryBetween(Short value1, Short value2) {
            addCriterion("PROC_CATEGORY between", value1, value2, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcCategoryNotBetween(Short value1, Short value2) {
            addCriterion("PROC_CATEGORY not between", value1, value2, "procCategory");
            return (Criteria) this;
        }

        public Criteria andProcTypeIsNull() {
            addCriterion("PROC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andProcTypeIsNotNull() {

            addCriterion("PROC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProcTypeEqualTo(Short value) {

            addCriterion("PROC_TYPE =", value, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeNotEqualTo(Short value) {

            addCriterion("PROC_TYPE <>", value, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeGreaterThan(Short value) {

            addCriterion("PROC_TYPE >", value, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeGreaterThanOrEqualTo(Short value) {

            addCriterion("PROC_TYPE >=", value, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeLessThan(Short value) {

            addCriterion("PROC_TYPE <", value, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeLessThanOrEqualTo(Short value) {

            addCriterion("PROC_TYPE <=", value, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeIn(List<Short> values) {

            addCriterion("PROC_TYPE in", values, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeNotIn(List<Short> values) {

            addCriterion("PROC_TYPE not in", values, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeBetween(Short value1, Short value2) {

            addCriterion("PROC_TYPE between", value1, value2, "procType");
            return (Criteria) this;
        }

        public Criteria andProcTypeNotBetween(Short value1, Short value2) {

            addCriterion("PROC_TYPE not between", value1, value2, "procType");
            return (Criteria) this;
        }

        public Criteria andTelnetPortIsNull() {

            addCriterion("TELNET_PORT is null");
            return (Criteria) this;
        }

        public Criteria andTelnetPortIsNotNull() {

            addCriterion("TELNET_PORT is not null");
            return (Criteria) this;
        }

        public Criteria andTelnetPortEqualTo(Integer value) {

            addCriterion("TELNET_PORT =", value, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortNotEqualTo(Integer value) {

            addCriterion("TELNET_PORT <>", value, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortGreaterThan(Integer value) {

            addCriterion("TELNET_PORT >", value, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortGreaterThanOrEqualTo(Integer value) {

            addCriterion("TELNET_PORT >=", value, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortLessThan(Integer value) {

            addCriterion("TELNET_PORT <", value, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortLessThanOrEqualTo(Integer value) {

            addCriterion("TELNET_PORT <=", value, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortIn(List<Integer> values) {

            addCriterion("TELNET_PORT in", values, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortNotIn(List<Integer> values) {

            addCriterion("TELNET_PORT not in", values, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortBetween(Integer value1, Integer value2) {

            addCriterion("TELNET_PORT between", value1, value2, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andTelnetPortNotBetween(Integer value1, Integer value2) {

            addCriterion("TELNET_PORT not between", value1, value2, "telnetPort");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {

            addCriterion("METHOD is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {

            addCriterion("METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(Short value) {

            addCriterion("METHOD =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(Short value) {

            addCriterion("METHOD <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(Short value) {

            addCriterion("METHOD >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(Short value) {

            addCriterion("METHOD >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(Short value) {

            addCriterion("METHOD <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(Short value) {

            addCriterion("METHOD <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<Short> values) {

            addCriterion("METHOD in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<Short> values) {

            addCriterion("METHOD not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(Short value1, Short value2) {

            addCriterion("METHOD between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(Short value1, Short value2) {

            addCriterion("METHOD not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andRuleNoIsNull() {

            addCriterion("RULE_NO is null");
            return (Criteria) this;
        }

        public Criteria andRuleNoIsNotNull() {

            addCriterion("RULE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRuleNoEqualTo(Short value) {

            addCriterion("RULE_NO =", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotEqualTo(Short value) {

            addCriterion("RULE_NO <>", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoGreaterThan(Short value) {

            addCriterion("RULE_NO >", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoGreaterThanOrEqualTo(Short value) {

            addCriterion("RULE_NO >=", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoLessThan(Short value) {

            addCriterion("RULE_NO <", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoLessThanOrEqualTo(Short value) {

            addCriterion("RULE_NO <=", value, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoIn(List<Short> values) {

            addCriterion("RULE_NO in", values, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotIn(List<Short> values) {

            addCriterion("RULE_NO not in", values, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoBetween(Short value1, Short value2) {

            addCriterion("RULE_NO between", value1, value2, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andRuleNoNotBetween(Short value1, Short value2) {

            addCriterion("RULE_NO not between", value1, value2, "ruleNo");
            return (Criteria) this;
        }

        public Criteria andUseFlagIsNull() {

            addCriterion("USE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andUseFlagIsNotNull() {

            addCriterion("USE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andUseFlagEqualTo(Short value) {

            addCriterion("USE_FLAG =", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotEqualTo(Short value) {

            addCriterion("USE_FLAG <>", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagGreaterThan(Short value) {

            addCriterion("USE_FLAG >", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagGreaterThanOrEqualTo(Short value) {

            addCriterion("USE_FLAG >=", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLessThan(Short value) {

            addCriterion("USE_FLAG <", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLessThanOrEqualTo(Short value) {

            addCriterion("USE_FLAG <=", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagIn(List<Short> values) {

            addCriterion("USE_FLAG in", values, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotIn(List<Short> values) {

            addCriterion("USE_FLAG not in", values, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagBetween(Short value1, Short value2) {

            addCriterion("USE_FLAG between", value1, value2, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotBetween(Short value1, Short value2) {

            addCriterion("USE_FLAG not between", value1, value2, "useFlag");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNull() {

            addCriterion("ABBREVIATION is null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNotNull() {

            addCriterion("ABBREVIATION is not null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationEqualTo(String value) {

            addCriterion("ABBREVIATION =", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotEqualTo(String value) {

            addCriterion("ABBREVIATION <>", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThan(String value) {

            addCriterion("ABBREVIATION >", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThanOrEqualTo(String value) {

            addCriterion("ABBREVIATION >=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThan(String value) {

            addCriterion("ABBREVIATION <", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThanOrEqualTo(String value) {

            addCriterion("ABBREVIATION <=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLike(String value) {

            addCriterion("ABBREVIATION like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotLike(String value) {

            addCriterion("ABBREVIATION not like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIn(List<String> values) {

            addCriterion("ABBREVIATION in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotIn(List<String> values) {

            addCriterion("ABBREVIATION not in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationBetween(String value1, String value2) {

            addCriterion("ABBREVIATION between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotBetween(String value1, String value2) {

            addCriterion("ABBREVIATION not between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andExePathIsNull() {

            addCriterion("EXE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andExePathIsNotNull() {

            addCriterion("EXE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andExePathEqualTo(String value) {

            addCriterion("EXE_PATH =", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathNotEqualTo(String value) {

            addCriterion("EXE_PATH <>", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathGreaterThan(String value) {

            addCriterion("EXE_PATH >", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathGreaterThanOrEqualTo(String value) {

            addCriterion("EXE_PATH >=", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathLessThan(String value) {

            addCriterion("EXE_PATH <", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathLessThanOrEqualTo(String value) {

            addCriterion("EXE_PATH <=", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathLike(String value) {

            addCriterion("EXE_PATH like", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathNotLike(String value) {

            addCriterion("EXE_PATH not like", value, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathIn(List<String> values) {

            addCriterion("EXE_PATH in", values, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathNotIn(List<String> values) {

            addCriterion("EXE_PATH not in", values, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathBetween(String value1, String value2) {

            addCriterion("EXE_PATH between", value1, value2, "exePath");
            return (Criteria) this;
        }

        public Criteria andExePathNotBetween(String value1, String value2) {

            addCriterion("EXE_PATH not between", value1, value2, "exePath");
            return (Criteria) this;
        }

        public Criteria andArgumentIsNull() {

            addCriterion("ARGUMENT is null");
            return (Criteria) this;
        }

        public Criteria andArgumentIsNotNull() {

            addCriterion("ARGUMENT is not null");
            return (Criteria) this;
        }

        public Criteria andArgumentEqualTo(String value) {

            addCriterion("ARGUMENT =", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotEqualTo(String value) {

            addCriterion("ARGUMENT <>", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentGreaterThan(String value) {

            addCriterion("ARGUMENT >", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentGreaterThanOrEqualTo(String value) {

            addCriterion("ARGUMENT >=", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentLessThan(String value) {

            addCriterion("ARGUMENT <", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentLessThanOrEqualTo(String value) {

            addCriterion("ARGUMENT <=", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentLike(String value) {

            addCriterion("ARGUMENT like", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotLike(String value) {

            addCriterion("ARGUMENT not like", value, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentIn(List<String> values) {

            addCriterion("ARGUMENT in", values, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotIn(List<String> values) {

            addCriterion("ARGUMENT not in", values, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentBetween(String value1, String value2) {

            addCriterion("ARGUMENT between", value1, value2, "argument");
            return (Criteria) this;
        }

        public Criteria andArgumentNotBetween(String value1, String value2) {

            addCriterion("ARGUMENT not between", value1, value2, "argument");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table PROCESS
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {

            return condition;
        }

        public Object getValue() {

            return value;
        }

        public Object getSecondValue() {

            return secondValue;
        }

        public boolean isNoValue() {

            return noValue;
        }

        public boolean isSingleValue() {

            return singleValue;
        }

        public boolean isBetweenValue() {

            return betweenValue;
        }

        public boolean isListValue() {

            return listValue;
        }

        public String getTypeHandler() {

            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table PROCESS
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 15:13:24 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
