package net.muratec.mcs.model;

public class Route extends RouteKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROUTE.FUNC_OPT
     * @mbg.generated
     */
    private Short funcOpt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROUTE.ROUTE_COUNT
     * @mbg.generated
     */
    private Short routeCount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROUTE.ENABLE_FLAG
     * @mbg.generated
     */
    private Short enableFlag;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROUTE.FUNC_OPT
     * @return  the value of ROUTE.FUNC_OPT
     * @mbg.generated
     */
    public Short getFuncOpt() {

        return funcOpt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROUTE.FUNC_OPT
     * @param funcOpt  the value for ROUTE.FUNC_OPT
     * @mbg.generated
     */
    public void setFuncOpt(Short funcOpt) {

        this.funcOpt = funcOpt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROUTE.ROUTE_COUNT
     * @return  the value of ROUTE.ROUTE_COUNT
     * @mbg.generated
     */
    public Short getRouteCount() {

        return routeCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROUTE.ROUTE_COUNT
     * @param routeCount  the value for ROUTE.ROUTE_COUNT
     * @mbg.generated
     */
    public void setRouteCount(Short routeCount) {

        this.routeCount = routeCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROUTE.ENABLE_FLAG
     * @return  the value of ROUTE.ENABLE_FLAG
     * @mbg.generated
     */
    public Short getEnableFlag() {

        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROUTE.ENABLE_FLAG
     * @param enableFlag  the value for ROUTE.ENABLE_FLAG
     * @mbg.generated
     */
    public void setEnableFlag(Short enableFlag) {

        this.enableFlag = enableFlag;
    }
}
