package net.muratec.mcs.model;

public class TableCompConfig extends TableCompConfigKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG.COL_DISPLAY_FLAG_LIST
     * @mbg.generated
     */
    private String colDisplayFlagList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG.COL_ORDER_LIST
     * @mbg.generated
     */
    private String colOrderList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG.PAGE_RECORDS
     * @mbg.generated
     */
    private Short pageRecords;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG.COL_DISPLAY_FLAG_LIST
     * @return  the value of TABLE_COMP_CONFIG.COL_DISPLAY_FLAG_LIST
     * @mbg.generated
     */
    public String getColDisplayFlagList() {

        return colDisplayFlagList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG.COL_DISPLAY_FLAG_LIST
     * @param colDisplayFlagList  the value for TABLE_COMP_CONFIG.COL_DISPLAY_FLAG_LIST
     * @mbg.generated
     */
    public void setColDisplayFlagList(String colDisplayFlagList) {

        this.colDisplayFlagList = colDisplayFlagList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG.COL_ORDER_LIST
     * @return  the value of TABLE_COMP_CONFIG.COL_ORDER_LIST
     * @mbg.generated
     */
    public String getColOrderList() {

        return colOrderList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG.COL_ORDER_LIST
     * @param colOrderList  the value for TABLE_COMP_CONFIG.COL_ORDER_LIST
     * @mbg.generated
     */
    public void setColOrderList(String colOrderList) {

        this.colOrderList = colOrderList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG.PAGE_RECORDS
     * @return  the value of TABLE_COMP_CONFIG.PAGE_RECORDS
     * @mbg.generated
     */
    public Short getPageRecords() {

        return pageRecords;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG.PAGE_RECORDS
     * @param pageRecords  the value for TABLE_COMP_CONFIG.PAGE_RECORDS
     * @mbg.generated
     */
    public void setPageRecords(Short pageRecords) {

        this.pageRecords = pageRecords;
    }
}
