package net.muratec.mcs.model;

public class TableCompConfigM {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.TABLE_COMP_ID
     * @mbg.generated
     */
    private String tableCompId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.COL_ID_LIST
     * @mbg.generated
     */
    private String colIdList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.COL_NAME_KEY_LIST
     * @mbg.generated
     */
    private String colNameKeyList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.COL_ALIGN_LIST
     * @mbg.generated
     */
    private String colAlignList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.COL_UNIQUE_FLAG_LIST
     * @mbg.generated
     */
    private String colUniqueFlagList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.COL_DISPLAY_FLAG_LIST
     * @mbg.generated
     */
    private String colDisplayFlagList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.COL_ORDER_LIST
     * @mbg.generated
     */
    private String colOrderList;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TABLE_COMP_CONFIG_M.PAGE_RECORDS
     * @mbg.generated
     */
    private Short pageRecords;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.TABLE_COMP_ID
     * @return  the value of TABLE_COMP_CONFIG_M.TABLE_COMP_ID
     * @mbg.generated
     */
    public String getTableCompId() {

        return tableCompId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.TABLE_COMP_ID
     * @param tableCompId  the value for TABLE_COMP_CONFIG_M.TABLE_COMP_ID
     * @mbg.generated
     */
    public void setTableCompId(String tableCompId) {

        this.tableCompId = tableCompId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.COL_ID_LIST
     * @return  the value of TABLE_COMP_CONFIG_M.COL_ID_LIST
     * @mbg.generated
     */
    public String getColIdList() {

        return colIdList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.COL_ID_LIST
     * @param colIdList  the value for TABLE_COMP_CONFIG_M.COL_ID_LIST
     * @mbg.generated
     */
    public void setColIdList(String colIdList) {

        this.colIdList = colIdList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.COL_NAME_KEY_LIST
     * @return  the value of TABLE_COMP_CONFIG_M.COL_NAME_KEY_LIST
     * @mbg.generated
     */
    public String getColNameKeyList() {

        return colNameKeyList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.COL_NAME_KEY_LIST
     * @param colNameKeyList  the value for TABLE_COMP_CONFIG_M.COL_NAME_KEY_LIST
     * @mbg.generated
     */
    public void setColNameKeyList(String colNameKeyList) {

        this.colNameKeyList = colNameKeyList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.COL_ALIGN_LIST
     * @return  the value of TABLE_COMP_CONFIG_M.COL_ALIGN_LIST
     * @mbg.generated
     */
    public String getColAlignList() {

        return colAlignList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.COL_ALIGN_LIST
     * @param colAlignList  the value for TABLE_COMP_CONFIG_M.COL_ALIGN_LIST
     * @mbg.generated
     */
    public void setColAlignList(String colAlignList) {

        this.colAlignList = colAlignList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.COL_UNIQUE_FLAG_LIST
     * @return  the value of TABLE_COMP_CONFIG_M.COL_UNIQUE_FLAG_LIST
     * @mbg.generated
     */
    public String getColUniqueFlagList() {

        return colUniqueFlagList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.COL_UNIQUE_FLAG_LIST
     * @param colUniqueFlagList  the value for TABLE_COMP_CONFIG_M.COL_UNIQUE_FLAG_LIST
     * @mbg.generated
     */
    public void setColUniqueFlagList(String colUniqueFlagList) {

        this.colUniqueFlagList = colUniqueFlagList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.COL_DISPLAY_FLAG_LIST
     * @return  the value of TABLE_COMP_CONFIG_M.COL_DISPLAY_FLAG_LIST
     * @mbg.generated
     */
    public String getColDisplayFlagList() {

        return colDisplayFlagList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.COL_DISPLAY_FLAG_LIST
     * @param colDisplayFlagList  the value for TABLE_COMP_CONFIG_M.COL_DISPLAY_FLAG_LIST
     * @mbg.generated
     */
    public void setColDisplayFlagList(String colDisplayFlagList) {

        this.colDisplayFlagList = colDisplayFlagList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.COL_ORDER_LIST
     * @return  the value of TABLE_COMP_CONFIG_M.COL_ORDER_LIST
     * @mbg.generated
     */
    public String getColOrderList() {

        return colOrderList;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.COL_ORDER_LIST
     * @param colOrderList  the value for TABLE_COMP_CONFIG_M.COL_ORDER_LIST
     * @mbg.generated
     */
    public void setColOrderList(String colOrderList) {

        this.colOrderList = colOrderList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TABLE_COMP_CONFIG_M.PAGE_RECORDS
     * @return  the value of TABLE_COMP_CONFIG_M.PAGE_RECORDS
     * @mbg.generated
     */
    public Short getPageRecords() {

        return pageRecords;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TABLE_COMP_CONFIG_M.PAGE_RECORDS
     * @param pageRecords  the value for TABLE_COMP_CONFIG_M.PAGE_RECORDS
     * @mbg.generated
     */
    public void setPageRecords(Short pageRecords) {

        this.pageRecords = pageRecords;
    }
}
