package net.muratec.mcs.model;

public class TakeoverRule {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TAKEOVER_RULE.RULE_NO
     * @mbg.generated
     */
    private Short ruleNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TAKEOVER_RULE.DESCRIPTION
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TAKEOVER_RULE.RULE_NO
     * @return  the value of TAKEOVER_RULE.RULE_NO
     * @mbg.generated
     */
    public Short getRuleNo() {

        return ruleNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TAKEOVER_RULE.RULE_NO
     * @param ruleNo  the value for TAKEOVER_RULE.RULE_NO
     * @mbg.generated
     */
    public void setRuleNo(Short ruleNo) {

        this.ruleNo = ruleNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TAKEOVER_RULE.DESCRIPTION
     * @return  the value of TAKEOVER_RULE.DESCRIPTION
     * @mbg.generated
     */
    public String getDescription() {

        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TAKEOVER_RULE.DESCRIPTION
     * @param description  the value for TAKEOVER_RULE.DESCRIPTION
     * @mbg.generated
     */
    public void setDescription(String description) {

        this.description = description;
    }
}
