package net.muratec.mcs.model;

public class TraceLogLevel {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TRACE_LOG_LEVEL.PROC_NAME
     * @mbg.generated
     */
    private String procName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TRACE_LOG_LEVEL.LOG_LEVEL
     * @mbg.generated
     */
    private Short logLevel;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TRACE_LOG_LEVEL.INTERVAL
     * @mbg.generated
     */
    private Short interval;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column TRACE_LOG_LEVEL.DIRECTORY
     * @mbg.generated
     */
    private String directory;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TRACE_LOG_LEVEL.PROC_NAME
     * @return  the value of TRACE_LOG_LEVEL.PROC_NAME
     * @mbg.generated
     */
    public String getProcName() {

        return procName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TRACE_LOG_LEVEL.PROC_NAME
     * @param procName  the value for TRACE_LOG_LEVEL.PROC_NAME
     * @mbg.generated
     */
    public void setProcName(String procName) {

        this.procName = procName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TRACE_LOG_LEVEL.LOG_LEVEL
     * @return  the value of TRACE_LOG_LEVEL.LOG_LEVEL
     * @mbg.generated
     */
    public Short getLogLevel() {

        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TRACE_LOG_LEVEL.LOG_LEVEL
     * @param logLevel  the value for TRACE_LOG_LEVEL.LOG_LEVEL
     * @mbg.generated
     */
    public void setLogLevel(Short logLevel) {

        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TRACE_LOG_LEVEL.INTERVAL
     * @return  the value of TRACE_LOG_LEVEL.INTERVAL
     * @mbg.generated
     */
    public Short getInterval() {

        return interval;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TRACE_LOG_LEVEL.INTERVAL
     * @param interval  the value for TRACE_LOG_LEVEL.INTERVAL
     * @mbg.generated
     */
    public void setInterval(Short interval) {

        this.interval = interval;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column TRACE_LOG_LEVEL.DIRECTORY
     * @return  the value of TRACE_LOG_LEVEL.DIRECTORY
     * @mbg.generated
     */
    public String getDirectory() {

        return directory;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column TRACE_LOG_LEVEL.DIRECTORY
     * @param directory  the value for TRACE_LOG_LEVEL.DIRECTORY
     * @mbg.generated
     */
    public void setDirectory(String directory) {

        this.directory = directory;
    }
}
