package net.muratec.mcs.model;

public class VipRltKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column VIP_RLT.SERVICE_ID
     * @mbg.generated
     */
    private String serviceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column VIP_RLT.NODE_ID
     * @mbg.generated
     */
    private Short nodeId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column VIP_RLT.SERVICE_ID
     * @return  the value of VIP_RLT.SERVICE_ID
     * @mbg.generated
     */
    public String getServiceId() {

        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column VIP_RLT.SERVICE_ID
     * @param serviceId  the value for VIP_RLT.SERVICE_ID
     * @mbg.generated
     */
    public void setServiceId(String serviceId) {

        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column VIP_RLT.NODE_ID
     * @return  the value of VIP_RLT.NODE_ID
     * @mbg.generated
     */
    public Short getNodeId() {

        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column VIP_RLT.NODE_ID
     * @param nodeId  the value for VIP_RLT.NODE_ID
     * @mbg.generated
     */
    public void setNodeId(Short nodeId) {

        this.nodeId = nodeId;
    }
}
