package net.muratec.mcs.model;

public class VipRlt extends VipRltKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column VIP_RLT.VIP_ID
     * @mbg.generated
     */
    private String vipId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column VIP_RLT.INTERFACE_ID
     * @mbg.generated
     */
    private String interfaceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column VIP_RLT.APPLY
     * @mbg.generated
     */
    private Short apply;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column VIP_RLT.VIP_ID
     * @return  the value of VIP_RLT.VIP_ID
     * @mbg.generated
     */
    public String getVipId() {

        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column VIP_RLT.VIP_ID
     * @param vipId  the value for VIP_RLT.VIP_ID
     * @mbg.generated
     */
    public void setVipId(String vipId) {

        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column VIP_RLT.INTERFACE_ID
     * @return  the value of VIP_RLT.INTERFACE_ID
     * @mbg.generated
     */
    public String getInterfaceId() {

        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column VIP_RLT.INTERFACE_ID
     * @param interfaceId  the value for VIP_RLT.INTERFACE_ID
     * @mbg.generated
     */
    public void setInterfaceId(String interfaceId) {

        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column VIP_RLT.APPLY
     * @return  the value of VIP_RLT.APPLY
     * @mbg.generated
     */
    public Short getApply() {

        return apply;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column VIP_RLT.APPLY
     * @param apply  the value for VIP_RLT.APPLY
     * @mbg.generated
     */
    public void setApply(Short apply) {

        this.apply = apply;
    }
}
